import type { PageContent } from "@/lib/content/types";
import type { BodySegment } from "@/lib/static-html/parsePage";
import type { SiteLocale } from "@/lib/i18n/types";

type Replacement = readonly [from: string, to: string];

const COMMON_OFF_PLAN_REPLACEMENTS: readonly Replacement[] = [
  ["Villas privéescious", "Private villas"],
  ["Private villascious", "Private villas"],
  ["Villas privéescious<br>\nSwimming Pool", "Private villas<br>\nSwimming pool"],
  ["Private villascious<br>\nSwimming Pool", "Private villas<br>\nSwimming pool"],
  ["of beautiful reality", "that fits your project"],
  ["of&nbsp;beautiful reality", "that fits your project"],
  ["Parc-like Parcing", "Park-like parking"],
  ["Parc-like&nbsp;Parcing", "Park-like parking"],
  ["Investirissement", "Investment"],
];

const EN_OFF_PLAN_REPLACEMENTS: readonly Replacement[] = [
  ["Langue", "Language"],
  ["<span>Sur plan</span>", "<span>Off-plan</span>"],
  ["Aller au contenu principal", "Skip to main content"],
  ["Accueil", "Home"],
  ["Navigation principale", "Main navigation"],
  ["Choisir la langue", "Choose language"],
  ["Demander l'accès", "Request access"],
  ["Nous contacter", "Contact us"],
  ["Immobilier privé à Marrakech", "Private real estate in Marrakech"],
  ["Marrakech, Maroc", "Marrakech, Morocco"],
  ["Accès privé sur demande", "Private access on request"],
  ["Tous droits réservés", "All rights reserved"],
  ["Confidentialité", "Privacy policy"],
  ["Mentions légales", "Legal notice"],
  ["Recevoir les opportunités privées", "Receive private opportunities"],
  ["Soyez informé des nouveaux projets sélectionnés à Marrakech.", "Stay informed about newly selected projects in Marrakech."],
  ["S'inscrire", "Subscribe"],
  ["Sur plan", "Off-plan"],
  ["Simulateur", "Simulator"],
  ["Contact", "Contact"],
  ["Une méthode devient signature", "A method becomes a signature"],
  ["Des programmes sur plan sélectionnés pour leur architecture, leur emplacement et leur potentiel patrimonial à Marrakech.", "Off-plan programmes selected for their architecture, location and long-term potential in Marrakech."],
  ["Négocier", "Negotiate"],
  ["Acquérir", "Acquire"],
  ["Comprendre votre projet", "Understand your project"],
  ["Cadrer votre recherche et votre horizon", "Define your search and time horizon"],
  ["Sélectionner les biens cohérents", "Select suitable properties"],
  ["Négocier avec discrétion", "Negotiate discreetly"],
  ["Stone Hammam", "Stone hammam"],
  ["Beauty hammam", "Elegant hammam"],
  ["Center à grandes ouvertures", "Central location with generous openings"],
  ["Appartements premium", "Premium apartments"],
  ["Adresses", "Addresses"],
  ["Intérieur", "Interior"],
  ["Rappel", "Callback"],
  ["Envoyer une demande", "Send a request"],
  ["Envoyer", "Send"],
  ["Nom", "Name"],
  ["Téléphone", "Phone"],
  ["Envoyer la demande", "Send request"],
  ["politique de confidentialité", "privacy policy"],
  ["Maison OFF MARKET", "OFF MARKET"],
  ["OFF MARKET — page d&amp;rsquo;accueil", "OFF MARKET — home"],
];

const NL_OFF_PLAN_REPLACEMENTS: readonly Replacement[] = [
  ["Choisir la langue", "Taal kiezen"],
  ["Langue", "Taal"],
  ["<span>Sur plan</span>", "<span>Nieuwbouw</span>"],
  ["Villas privéescious", "Privévilla's"],
  ["Private villascious", "Privévilla's"],
  ["Villas privéescious<br>\nSwimming Pool", "Privévilla's<br>\nZwembad"],
  ["Private villascious<br>\nSwimming Pool", "Privévilla's<br>\nZwembad"],
  ["of beautiful reality", "die bij uw project past"],
  ["of&nbsp;beautiful reality", "die bij uw project past"],
  ["Parc-like Parcing", "Parkachtige parking"],
  ["Parc-like&nbsp;Parcing", "Parkachtige parking"],
  ["Investirissement", "Investering"],
  ["Private villas", "Privévilla's"],
  ["that fits your project", "die bij uw project past"],
  ["Park-like parking", "Parkachtige parking"],
  ["Investment", "Investering"],
  ["Skip to main content", "Naar hoofdinhoud"],
  ["Accueil", "Home"],
  ["Navigation principale", "Hoofdnavigatie"],
  ["Choisir la langue", "Taal kiezen"],
  ["Demander l'accès", "Toegang aanvragen"],
  ["Immobilier privé à Marrakech", "Privévastgoed in Marrakech"],
  ["Nous contacter", "Contact opnemen"],
  ["Biens privés", "Privéaanbod"],
  ["OFF MARKET — page d&amp;rsquo;accueil", "OFF MARKET — startpagina"],
  ["Marrakech, Maroc", "Marrakech, Marokko"],
  ["Accès privé sur demande", "Private toegang op aanvraag"],
  ["Tous droits réservés", "Alle rechten voorbehouden"],
  ["Confidentialité", "Privacy"],
  ["Mentions légales", "Juridische vermeldingen"],
  ["Recevoir les opportunités privées", "Private opportuniteiten ontvangen"],
  [
    "Soyez informé des nouveaux projets sélectionnés à Marrakech.",
    "Blijf op de hoogte van nieuwe geselecteerde projecten in Marrakech.",
  ],
  ["S'inscrire", "Inschrijven"],
  ["Sur plan", "Nieuwbouw"],
  ["Simulateur", "Simulator"],
  ["Contact", "Contact"],
  ["LA SÉLECTION À PORTÉE DE MAIN", "DE SELECTIE BINNEN HANDBEREIK"],
  ["La sélection à portée de main", "De selectie binnen handbereik"],
  [
    "OFF MARKET sécurise chaque parcours jusqu'à la décision finale, avec un accompagnement clair et discret.",
    "OFF MARKET begeleidt elk traject tot aan de eindbeslissing, met heldere en discrete ondersteuning.",
  ],
  [
    "OFF MARKET sécurise chaque parcours jusqu&rsquo;à la décision finale, avec un accompagnement clair et discret.",
    "OFF MARKET begeleidt elk traject tot aan de eindbeslissing, met heldere en discrete ondersteuning.",
  ],
  [
    "OFF MARKET sécurise chaque parcours jusqu&amp;rsquo;à la décision finale, avec un accompagnement clair et discret.",
    "OFF MARKET begeleidt elk traject tot aan de eindbeslissing, met heldere en discrete ondersteuning.",
  ],
  [
    "Nous sécurisons le parcours jusqu à la décision finale, avec un accompagnement clair et discret.",
    "Wij begeleiden het traject tot aan de eindbeslissing, met heldere en discrete ondersteuning.",
  ],
  [
    "Nous sécurisons le parcours jusqu&amp;rsquo;à la décision finale, avec un accompagnement clair et discret.",
    "Wij begeleiden het traject tot aan de eindbeslissing, met heldere en discrete ondersteuning.",
  ],
  [
    "Nous accompagnons les échanges, les vérifications et la lecture stratégique de l&rsquo;opportunité.",
    "Wij begeleiden de gesprekken, controles en strategische beoordeling van de opportuniteit.",
  ],
  [
    "Nous accompagnons les échanges, les vérifications et la lecture stratégique de l&amp;rsquo;opportunité.",
    "Wij begeleiden de gesprekken, controles en strategische beoordeling van de opportuniteit.",
  ],
  [
    "Nous accompagnons les échanges, les vérifications et la lecture stratégique de l opportunité.",
    "Wij begeleiden de gesprekken, controles en strategische beoordeling van de opportuniteit.",
  ],
  [
    "Marrakech se révèle autrement selon l&rsquo;adresse : prestige central, rendement urbain, villas privées ou horizon patrimonial sur l&rsquo;Atlas.",
    "Marrakech toont zich anders naargelang het adres: centrale prestige, stedelijk rendement, private villa's of patrimoniaal perspectief richting de Atlas.",
  ],
  [
    "Marrakech se révèle autrement selon l&amp;rsquo;adresse : prestige central, rendement urbain, villas privées ou horizon patrimonial sur l&amp;rsquo;Atlas.",
    "Marrakech toont zich anders naargelang het adres: centrale prestige, stedelijk rendement, private villa's of patrimoniaal perspectief richting de Atlas.",
  ],
  ["Une méthode devient signature", "Een methode wordt een signatuur"],
  ["Une méthode<br>\ndevient signature", "Een methode<br>\nwordt een signatuur"],
  [
    "Des programmes sur plan sélectionnés pour leur architecture, leur emplacement et leur potentiel patrimonial à Marrakech.",
    "Nieuwbouwprogramma's geselecteerd op architectuur, ligging en patrimoniaal potentieel in Marrakech.",
  ],
  [
    "Des programmes nieuwbouw geselecteerd op architectuur, ligging en patrimoniaal potentieel in Marrakech.",
    "Nieuwbouwprogramma's geselecteerd op architectuur, ligging en patrimoniaal potentieel in Marrakech.",
  ],
  [
    "Nous cadrons votre recherche, votre horizon, votre budget et votre logique d&rsquo;achat avec méthode et discrétion.",
    "Wij kaderen uw zoektocht, horizon, budget en aankooplogica met methode en discretie.",
  ],
  [
    "Nous cadrons votre recherche, votre horizon, votre budget et votre logique d&amp;rsquo;achat avec méthode et discrétion.",
    "Wij kaderen uw zoektocht, horizon, budget en aankooplogica met methode en discretie.",
  ],
  ["Villas privéescious Swimming Pool", "Private villa's Zwembad"],
  ["Villas privéescious<br>\nSwimming Pool", "Private villa's<br>\nZwembad"],
  [
    "Nous filtrons les biens selon leur adresse, leur potentiel, leur cohérence et leur niveau de confidentialité.",
    "Wij filteren vastgoed volgens adres, potentieel, samenhang en vertrouwelijkheidsniveau.",
  ],
  ["Comprendre votre projet", "Uw project begrijpen"],
  [
    "Comprendre votre projet et votre horizon patrimonial",
    "Uw project en patrimoniale horizon begrijpen",
  ],
  ["Négocier", "Onderhandelen"],
  [
    "Des adresses singulières dans les quartiers historiques, sélectionnées pour leur charme, leur potentiel et leur rareté.",
    "Bijzondere adressen in historische wijken, geselecteerd op charme, potentieel en zeldzaamheid.",
  ],
  ["Acquérir", "Verwerven"],
  ["Stone Hammam", "Stenen hammam"],
  ["Appartements premium", "Premium appartementen"],
  ["Beauty hammam", "Elegante hammam"],
  ["Center à grandes ouvertures", "Centrum met grote openingen"],
  ["Center<br>\nà grandes ouvertures", "Centrum<br>\nmet grote openingen"],
  ["Beauty</span>", "Elegante</span>"],
  [
    "Winding paths, paved with gray granite, resemble creeks and riverbeds that flow gently around OFF MARKET. White froth of hydrangeas and slender torsos of shadberries, suspended above invisible water, become a picturesque backdrop for a riverside walk.",
    "Slingerpaadjes in grijs graniet begeleiden de wandeling rond het project. Beplanting, schaduw en minerale lijnen vormen een rustig decor voor een discreet woonritme.",
  ],
  [
    "Winding paths, paved with&nbsp;gray granite, resemble creeks and riverbeds that flow gently around&nbsp;OFF MARKET. White froth of&nbsp;hydrangeas and slender torsos of&nbsp;shadberries, suspended above&nbsp;invisible water, become a&nbsp;picturesque backdrop for&nbsp;a&nbsp;riverside walk.",
    "Slingerpaadjes in grijs graniet begeleiden de wandeling rond het project. Beplanting, schaduw en minerale lijnen vormen een rustig decor voor een discreet woonritme.",
  ],
  ["OMBRES ET PERSPECTIVES", "SCHADUW EN PERSPECTIEF"],
  ["Ombres et perspectives", "Schaduw en perspectief"],
  ["COUR INTÉRIEURE", "BINNENPATIO"],
  ["Cour intérieure", "Binnenpatio"],
  ["JARDINS STRUCTURANTS", "STRUCTURERENDE TUINEN"],
  ["Jardins structurants", "Structurerende tuinen"],
  [
    "Une méthode d'acquisition en quatre étapes : comprendre, sélectionner, négocier, acquérir.",
    "Een aankoopmethode in vier stappen: begrijpen, selecteren, onderhandelen, verwerven.",
  ],
  [
    "Une méthode d&rsquo;acquisition en quatre étapes : comprendre, sélectionner, négocier, acquérir.",
    "Een aankoopmethode in vier stappen: begrijpen, selecteren, onderhandelen, verwerven.",
  ],
  [
    "Une méthode d&amp;rsquo;acquisition en quatre étapes : comprendre, sélectionner, négocier, acquérir.",
    "Een aankoopmethode in vier stappen: begrijpen, selecteren, onderhandelen, verwerven.",
  ],
  [
    "Une méthode d acquisition en quatre étapes : comprendre, sélectionner, négocier, acquérir.",
    "Een aankoopmethode in vier stappen: begrijpen, selecteren, onderhandelen, verwerven.",
  ],
  [
    "Une methode d acquisition en quatre étapes : comprendre, sélectionner, négocier, acquérir.",
    "Een aankoopmethode in vier stappen: begrijpen, selecteren, onderhandelen, verwerven.",
  ],
  ["Cadrer votre recherche et votre horizon", "Uw zoektocht en horizon kaderen"],
  ["Sélectionner les biens cohérents", "Samenhangende panden selecteren"],
  ["Négocier avec discrétion", "Discreet onderhandelen"],
  [
    "OFF MARKET compose une sélection of beautiful reality.",
    "OFF MARKET stelt een selectie samen die aansluit bij uw aankooplogica.",
  ],
  [
    "OFF MARKET compose une sélection<br>\nof&nbsp;beautiful reality.",
    "OFF MARKET stelt een selectie samen<br>\ndie aansluit bij uw aankooplogica.",
  ],
  [
    "OFF MARKET compose une sélection of beautiful reality.",
    "OFF MARKET stelt een selectie samen die aansluit bij uw aankooplogica.",
  ],
  ["PERMANENT OUTDOOR RECREATION SPACES", "PERMANENTE BUITENRUIMTES"],
  ["VIDEO-MONITORED PLAYGROUNDS", "BEVEILIGDE SPEELZONES"],
  ["PORTABLE OUTDOOR FURNITURE", "FLEXIBEL BUITENMEUBILAIR"],
  [
    "Route de l&rsquo;Ourika — villas, Atlas et horizon long terme.",
    "Route de l'Ourika — villa's, Atlas en langetermijnperspectief.",
  ],
  ["À quelques minutes des adresses patrimoniales.", "Op enkele minuten van patrimoniale adressen."],
  ["discrète Palmeraie", "Discrete Palmeraie"],
  ["PALETTE SOBRE OF BLOSSOMS", "INGETOGEN GROENPALET"],
  [
    "Agdal — adresses résidentielles modernes, jardins royaux à proximité et lecture patrimoniale claire.",
    "Agdal — moderne residentiële adressen, koninklijke tuinen vlakbij en een heldere patrimoniale lezing.",
  ],
  ["Panoramique Terraces", "Panoramische terrassen"],
  [
    "Des terrasses de vue où la lumière, la pierre et le jardin composent un cadre de vie discret et mémorable.",
    "Uitzichtterrassen waar licht, steen en tuin samen een discreet en memorabel leefkader vormen.",
  ],
  ["VOLUMES PATRIMONIAUX", "PATRIMONIALE VOLUMES"],
  ["Volumes patrimoniaux", "Patrimoniale volumes"],
  ["TRANSPARENT PANORAMIC RAILING", "TRANSPARANTE PANORAMISCHE BALUSTRADE"],
  ["Transparent panoramic railing", "Transparante panoramische balustrade"],
  ["LUMIÈRE MAÎTRISÉE", "BEHEERST LICHT"],
  ["Lumière maîtrisée", "Beheerst licht"],
  ["Parc-like Parcing", "Parkachtige parking"],
  [
    "Chaque détail est pensé avec exigence : volumes, matières et lumière au service d'une acquisition patrimoniale cohérente.",
    "Elk detail is zorgvuldig doordacht: volumes, materialen en licht in dienst van een coherente patrimoniale aankoop.",
  ],
  [
    "Chaque détail est pensé avec exigence : volumes, matières et lumière au service d&rsquo;une acquisition patrimoniale cohérente.",
    "Elk detail is zorgvuldig doordacht: volumes, materialen en licht in dienst van een coherente patrimoniale aankoop.",
  ],
  [
    "Chaque détail est pensé avec exigence : volumes, matières et lumière au service d&amp;rsquo;une acquisition patrimoniale cohérente.",
    "Elk detail is zorgvuldig doordacht: volumes, materialen en licht in dienst van een coherente patrimoniale aankoop.",
  ],
  ["Intérieurs d&rsquo;exception", "Uitzonderlijke interieurs"],
  ["Intérieurs d&amp;rsquo;exception", "Uitzonderlijke interieurs"],
  ["Interieurs d exception", "Uitzonderlijke interieurs"],
  ["Two levels", "Twee niveaus"],
  ["Investirissement", "Investering"],
  ["OASIS CONFIDENTIELLE AU CŒUR DE MARRAKECH", "VERTROUWELIJKE OASE IN HET HART VAN MARRAKECH"],
  ["OASIS CONFIDENTIELLE AU C&amp;OElig;UR DE MARRAKECH", "VERTROUWELIJKE OASE IN HET HART VAN MARRAKECH"],
  ["Adresses", "Adressen"],
  ["Intérieur", "Interieur"],
  ["Envoyer<br>\n                    une demande", "Een aanvraag<br>\n                    verzenden"],
  ["Envoyer une demande", "Een aanvraag verzenden"],
  [
    "Merci pour votre demande. Nous avons bien reçu votre message et vous recontacterons prochainement.",
    "Bedankt voor uw aanvraag. Wij hebben uw bericht goed ontvangen en nemen binnenkort contact met u op.",
  ],
  ["Demande", "Aanvraag"],
  ["Rappel", "Terugbelverzoek"],
  ["Nom", "Naam"],
  ["Téléphone", "Telefoon"],
  ["Envoyer la demande", "Aanvraag verzenden"],
  ["En cliquant, vous acceptez notre", "Door te klikken accepteert u onze"],
  ["à notre", "onze"],
  ["politique de confidentialité", "privacyverklaring"],
  ["Sélection :", "Selectie:"],
  ["Navigation fiche bien", "Navigatie vastgoedfiche"],
  ["Fermer la fiche", "Vastgoedfiche sluiten"],
  ["Plans transmis sur demande", "Plattegronden beschikbaar op aanvraag"],
  ["call time", "Tijdstip gesprek"],
  ["Permanent outdoor recreation spaces", "Permanente buitenruimtes"],
  ["Video-monitored playgrounds", "Beveiligde speelzones"],
  ["Portable outdoor furniture", "Flexibel buitenmeubilair"],
  ["Maison OFF MARKET", "OFF MARKET"],
  ["Veuillez pivoter votre appareil", "Draai uw apparaat"],
  ["Sélection privée d'opportunités immobilières à Marrakech.", "Private selectie van vastgoedkansen in Marrakech."],
  ["Veuillez pivoter votre appareil<br>to&nbsp;portrait mode", "Draai uw apparaat<br>naar portretmodus"],
  ["Veuillez pivoter votre appareil<br>to&nbsp;landscape mode", "Draai uw apparaat<br>naar landschapsmodus"],
  ["Veuillez pivoter votre appareil<br>to portrait mode", "Draai uw apparaat<br>naar portretmodus"],
  ["Veuillez pivoter votre appareil<br>to landscape mode", "Draai uw apparaat<br>naar landschapsmodus"],
  ["Bien immobilier de prestige OFF MARKET à Marrakech", "Exclusief vastgoed van OFF MARKET in Marrakech"],
  ["to portrait mode", "naar portretmodus"],
  ["to landscape mode", "naar landschapsmodus"],
];

const IT_OFF_PLAN_REPLACEMENTS: readonly Replacement[] = [
  ["Choisir la langue", "Scegli la lingua"],
  ["Langue", "Lingua"],
  ["Skip to main content", "Vai al contenuto principale"],
  ["Private properties", "Immobili privati"],
  ["Contact us", "Contattaci"],
  ["Request access", "Richiedi l'accesso"],
  ["Off-plan", "In costruzione"],
  ["Simulator", "Simulatore"],
  ["Private real estate in Marrakech", "Immobiliare privato a Marrakech"],
  ["Marrakech, Morocco", "Marrakech, Marocco"],
  ["Marrakech, Maroc", "Marrakech, Marocco"],
  ["Marrakech, Maroccoco", "Marrakech, Marocco"],
  ["Marrakech, Maroccocococo", "Marrakech, Marocco"],
  ["Marrakech, Maroccoco", "Marrakech, Marocco"],
  ["All rights reserved", "Tutti i diritti riservati"],
  ["Legal notice", "Note legali"],
  ["Privacy policy", "Informativa sulla privacy"],
  ["Villas privéescious Swimming Pool", "Ville private Piscina"],
  ["Villas privéescious<br>\nSwimming Pool", "Ville private<br>\nPiscina"],
  ["Ville privatecious Swimming Pool", "Ville private Piscina"],
  ["Ville privatecious<br>\nSwimming Pool", "Ville private<br>\nPiscina"],
  ["Private villascious", "Ville private"],
  ["Private villas", "Ville private"],
  ["Appartements premium", "Appartamenti premium"],
  ["Beauty hammam", "Hammam elegante"],
  ["Center à grandes ouvertures", "Centro con ampie aperture"],
  ["Center<br>\nà grandes ouvertures", "Centro<br>\ncon ampie aperture"],
  ["Beauty</span>", "Elegante</span>"],
  ["Stone Hammam", "Hammam in pietra"],
  ["Winding paths, paved with gray granite, resemble creeks and riverbeds that flow gently around OFF MARKET. White froth of hydrangeas and slender torsos of shadberries, suspended above invisible water, become a picturesque backdrop for a riverside walk.", "Sentieri sinuosi in granito grigio accompagnano la passeggiata intorno a OFF MARKET. Vegetazione, ombra e linee minerali creano uno scenario sereno per un ritmo abitativo discreto."],
  ["Winding paths, paved with&nbsp;gray granite, resemble creeks and riverbeds that flow gently around&nbsp;OFF MARKET. White froth of&nbsp;hydrangeas and slender torsos of&nbsp;shadberries, suspended above&nbsp;invisible water, become a&nbsp;picturesque backdrop for&nbsp;a&nbsp;riverside walk.", "Sentieri sinuosi in granito grigio accompagnano la passeggiata intorno a OFF MARKET. Vegetazione, ombra e linee minerali creano uno scenario sereno per un ritmo abitativo discreto."],
  ["Permanent outdoor recreation spaces", "Spazi ricreativi esterni permanenti"],
  ["Video-monitored playgrounds", "Aree gioco videosorvegliate"],
  ["Portable outdoor furniture", "Arredi esterni flessibili"],
  ["of beautiful reality", "coerente con il tuo progetto"],
  ["of&nbsp;beautiful reality", "coerente con il tuo progetto"],
  ["Internis d rsquo;exception", "Interni d'eccezione"],
  ["Internis d&amp;rsquo;exception", "Interni d'eccezione"],
  ["Two levels", "Due livelli"],
  ["Volumes patrimoniaux", "Volumi patrimoniali"],
  ["Transparent panoramic railing", "Parapetto panoramico trasparente"],
  ["Park-like Parcing", "Parcheggio immerso nel verde"],
  ["Investirissement", "Investimento"],
  ["Adresses", "Indirizzi"],
  ["Maison OFF MARKET", "OFF MARKET"],
  ["Envoyer une demande", "Invia una richiesta"],
  ["Rappel", "Richiamami"],
  ["Nomeee", "Nome"],
  ["Nomeeee", "Nome"],
  ["call time", "Orario della chiamata"],
  ["to portrait mode", "alla modalità verticale"],
  ["to landscape mode", "alla modalità orizzontale"],
  ["to&nbsp;portrait mode", "alla modalità verticale"],
  ["to&nbsp;landscape mode", "alla modalità orizzontale"],
  ["to portrait mode", "alla modalità verticale"],
  ["to landscape mode", "alla modalità orizzontale"],
  ["une demande", "una richiesta"],
  ["Bien immobilier de prestige OFF MARKET a Marrakech", "Immobiliare di prestigio OFF MARKET a Marrakech"],
  ["Richiestar un appel", "Richiedi un contatto"],
  ["Planimetrie &amp; configuration", "Planimetrie e configurazione"],
  ["Slide suivante", "Slide successiva"],
  ["5 photos", "5 foto"],
  ["su piano", "in costruzione"],
];

const ES_OFF_PLAN_REPLACEMENTS: readonly Replacement[] = [
  ["Choisir la langue", "Elegir idioma"],
  ["Langue", "Idioma"],
  ["<span>Sur plan</span>", "<span>Sobre plano</span>"],
  ["Sur plan", "Sobre plano"],
  ["Skip to main content", "Saltar al contenido principal"],
  ["Aller au contenu principal", "Saltar al contenido principal"],
  ["Accueil", "Inicio"],
  ["Navigation principale", "Navegación principal"],
  ["Demander l'accès", "Solicitar acceso"],
  ["Nous contacter", "Contactar"],
  ["Immobilier privé à Marrakech", "Inmobiliaria privada en Marrakech"],
  ["Marrakech, Maroc", "Marrakech, Marruecos"],
  ["Marrakech, Morocco", "Marrakech, Marruecos"],
  ["Accès privé sur demande", "Acceso privado bajo solicitud"],
  ["Tous droits réservés", "Todos los derechos reservados"],
  ["Confidentialité", "Privacidad"],
  ["Privacy policy", "Política de privacidad"],
  ["Mentions légales", "Aviso legal"],
  ["Recevoir les opportunités privées", "Recibir oportunidades privadas"],
  [
    "Soyez informé des nouveaux projets sélectionnés à Marrakech.",
    "Manténgase informado sobre los nuevos proyectos seleccionados en Marrakech.",
  ],
  ["S'inscrire", "Suscribirse"],
  ["Simulateur", "Simulador"],
  ["Contact", "Contacto"],
  ["Voir les détails du projet", "Ver detalles del proyecto"],
  ["LA SÉLECTION À PORTÉE DE MAIN", "LA SELECCIÓN AL ALCANCE"],
  ["La sélection à portée de main", "La selección al alcance"],
  [
    "OFF MARKET sécurise chaque parcours jusqu'à la décision finale, avec un accompagnement clair et discret.",
    "OFF MARKET acompaña cada recorrido hasta la decisión final con un seguimiento claro y discreto.",
  ],
  [
    "OFF MARKET sécurise chaque parcours jusqu&rsquo;à la décision finale, avec un accompagnement clair et discret.",
    "OFF MARKET acompaña cada recorrido hasta la decisión final con un seguimiento claro y discreto.",
  ],
  [
    "OFF MARKET sécurise chaque parcours jusqu&amp;rsquo;à la décision finale, avec un accompagnement clair et discret.",
    "OFF MARKET acompaña cada recorrido hasta la decisión final con un seguimiento claro y discreto.",
  ],
  [
    "Nous accompagnons les échanges, les vérifications et la lecture stratégique de l&rsquo;opportunité.",
    "Acompañamos los intercambios, las verificaciones y la lectura estratégica de la oportunidad.",
  ],
  [
    "Marrakech se révèle autrement selon l&rsquo;adresse : prestige central, rendement urbain, villas privées ou horizon patrimonial sur l&rsquo;Atlas.",
    "Marrakech se revela de otra manera según la dirección: prestigio central, rendimiento urbano, villas privadas u horizonte patrimonial hacia el Atlas.",
  ],
  ["Une méthode devient signature", "Un método se convierte en firma"],
  ["Une méthode<br>\ndevient signature", "Un método<br>\nse convierte en firma"],
  [
    "Des programmes sur plan sélectionnés pour leur architecture, leur emplacement et leur potentiel patrimonial à Marrakech.",
    "Programas sobre plano seleccionados por su arquitectura, ubicación y potencial patrimonial en Marrakech.",
  ],
  [
    "Nous cadrons votre recherche, votre horizon, votre budget et votre logique d&rsquo;achat avec méthode et discrétion.",
    "Estructuramos su búsqueda, horizonte, presupuesto y lógica de compra con método y discreción.",
  ],
  [
    "Nous filtrons les biens selon leur adresse, leur potentiel, leur cohérence et leur niveau de confidentialité.",
    "Filtramos las propiedades según su dirección, potencial, coherencia y nivel de confidencialidad.",
  ],
  ["Comprendre votre projet", "Entender su proyecto"],
  ["Cadrer votre recherche et votre horizon", "Definir su búsqueda y horizonte"],
  ["Sélectionner les biens cohérents", "Seleccionar propiedades coherentes"],
  ["Négocier avec discrétion", "Negociar con discreción"],
  ["Négocier", "Negociar"],
  ["Acquérir", "Adquirir"],
  ["Appartements premium", "Apartamentos premium"],
  ["Villas privéescious", "Villas privadas"],
  ["Private villascious", "Villas privadas"],
  ["Villas privéescious<br>\nSwimming Pool", "Villas privadas<br>\nPiscina"],
  ["Villas privéescious Swimming Pool", "Villas privadas Piscina"],
  ["Private villas", "Villas privadas"],
  ["Stone Hammam", "Hammam de piedra"],
  ["Beauty hammam", "Hammam elegante"],
  ["Center à grandes ouvertures", "Centro con grandes aperturas"],
  ["Center<br>\nà grandes ouvertures", "Centro<br>\ncon grandes aperturas"],
  ["Beauty</span>", "Elegante</span>"],
  [
    "Winding paths, paved with gray granite, resemble creeks and riverbeds that flow gently around OFF MARKET. White froth of hydrangeas and slender torsos of shadberries, suspended above invisible water, become a picturesque backdrop for a riverside walk.",
    "Senderos sinuosos de granito gris acompañan el paseo alrededor del proyecto. Vegetación, sombra y líneas minerales componen un entorno sereno para una vida discreta.",
  ],
  [
    "Winding paths, paved with&nbsp;gray granite, resemble creeks and riverbeds that flow gently around&nbsp;OFF MARKET. White froth of&nbsp;hydrangeas and slender torsos of&nbsp;shadberries, suspended above&nbsp;invisible water, become a&nbsp;picturesque backdrop for&nbsp;a&nbsp;riverside walk.",
    "Senderos sinuosos de granito gris acompañan el paseo alrededor del proyecto. Vegetación, sombra y líneas minerales componen un entorno sereno para una vida discreta.",
  ],
  ["OMBRES ET PERSPECTIVES", "SOMBRAS Y PERSPECTIVAS"],
  ["Ombres et perspectives", "Sombras y perspectivas"],
  ["COUR INTÉRIEURE", "PATIO INTERIOR"],
  ["Cour intérieure", "Patio interior"],
  ["JARDINS STRUCTURANTS", "JARDINES ESTRUCTURANTES"],
  ["Jardins structurants", "Jardines estructurantes"],
  [
    "Une méthode d'acquisition en quatre étapes : comprendre, sélectionner, négocier, acquérir.",
    "Un método de adquisición en cuatro etapas: entender, seleccionar, negociar y adquirir.",
  ],
  [
    "Une méthode d&rsquo;acquisition en quatre étapes : comprendre, sélectionner, négocier, acquérir.",
    "Un método de adquisición en cuatro etapas: entender, seleccionar, negociar y adquirir.",
  ],
  [
    "OFF MARKET compose une sélection<br>\nof&nbsp;beautiful reality.",
    "OFF MARKET compone una selección<br>\nadaptada a su proyecto.",
  ],
  ["of beautiful reality", "adaptada a su proyecto"],
  ["of&nbsp;beautiful reality", "adaptada a su proyecto"],
  ["PERMANENT OUTDOOR RECREATION SPACES", "ESPACIOS EXTERIORES PERMANENTES"],
  ["VIDEO-MONITORED PLAYGROUNDS", "ZONAS DE JUEGO VIDEOVIGILADAS"],
  ["PORTABLE OUTDOOR FURNITURE", "MOBILIARIO EXTERIOR FLEXIBLE"],
  [
    "Route de l&rsquo;Ourika — villas, Atlas et horizon long terme.",
    "Route de l'Ourika — villas, Atlas y horizonte a largo plazo.",
  ],
  ["À quelques minutes des adresses patrimoniales.", "A pocos minutos de direcciones patrimoniales."],
  ["discrète Palmeraie", "Palmeraie discreta"],
  ["PALETTE SOBRE OF BLOSSOMS", "PALETA VEGETAL SOBRIA"],
  [
    "Agdal — adresses résidentielles modernes, jardins royaux à proximité et lecture patrimoniale claire.",
    "Agdal — direcciones residenciales modernas, jardines reales cercanos y una lectura patrimonial clara.",
  ],
  ["Panoramique Terraces", "Terrazas panorámicas"],
  [
    "Des terrasses de vue où la lumière, la pierre et le jardin composent un cadre de vie discret et mémorable.",
    "Terrazas con vistas donde la luz, la piedra y el jardín componen un marco de vida discreto y memorable.",
  ],
  ["VOLUMES PATRIMONIAUX", "VOLÚMENES PATRIMONIALES"],
  ["Volumes patrimoniaux", "Volúmenes patrimoniales"],
  ["TRANSPARENT PANORAMIC RAILING", "BARANDILLA PANORÁMICA TRANSPARENTE"],
  ["Transparent panoramic railing", "Barandilla panorámica transparente"],
  ["LUMIÈRE MAÎTRISÉE", "LUZ CONTROLADA"],
  ["Lumière maîtrisée", "Luz controlada"],
  ["Parc-like Parcing", "Aparcamiento tipo parque"],
  [
    "Chaque détail est pensé avec exigence : volumes, matières et lumière au service d'une acquisition patrimoniale cohérente.",
    "Cada detalle se piensa con exigencia: volúmenes, materiales y luz al servicio de una adquisición patrimonial coherente.",
  ],
  [
    "Chaque détail est pensé avec exigence : volumes, matières et lumière au service d&rsquo;une acquisition patrimoniale cohérente.",
    "Cada detalle se piensa con exigencia: volúmenes, materiales y luz al servicio de una adquisición patrimonial coherente.",
  ],
  ["Intérieurs d&rsquo;exception", "Interiores excepcionales"],
  ["Intérieurs d&amp;rsquo;exception", "Interiores excepcionales"],
  ["Interieurs d exception", "Interiores excepcionales"],
  ["Two levels", "Dos niveles"],
  ["Investirissement", "Inversión"],
  ["OASIS CONFIDENTIELLE AU CŒUR DE MARRAKECH", "OASIS CONFIDENCIAL EN EL CORAZÓN DE MARRAKECH"],
  ["OASIS CONFIDENTIELLE AU C&amp;OElig;UR DE MARRAKECH", "OASIS CONFIDENCIAL EN EL CORAZÓN DE MARRAKECH"],
  ["Adresses", "Direcciones"],
  ["Intérieur", "Interior"],
  ["Envoyer<br>\n                    une demande", "Enviar<br>\n                    una solicitud"],
  ["Envoyer une demande", "Enviar una solicitud"],
  [
    "Merci pour votre demande. Nous avons bien reçu votre message et vous recontacterons prochainement.",
    "Gracias por su solicitud. Hemos recibido su mensaje y nos pondremos en contacto con usted próximamente.",
  ],
  ["Demande", "Solicitud"],
  ["Rappel", "Llamada"],
  ["Nom", "Nombre"],
  ["Téléphone", "Teléfono"],
  ["Envoyer la demande", "Enviar la solicitud"],
  ["En cliquant, vous acceptez notre", "Al hacer clic, acepta nuestra"],
  ["à notre", "nuestra"],
  ["politique de confidentialité", "política de privacidad"],
  ["Sélection :", "Selección:"],
  ["Navigation fiche bien", "Navegación de la ficha de propiedad"],
  ["Fermer la fiche", "Cerrar la ficha"],
  ["Plans transmis sur demande", "Planos disponibles previa solicitud"],
  ["call time", "Hora de llamada"],
  ["Maison OFF MARKET", "OFF MARKET"],
  ["Veuillez pivoter votre appareil", "Gire su dispositivo"],
  ["Veuillez pivoter votre appareil<br>to&nbsp;portrait mode", "Gire su dispositivo<br>al modo vertical"],
  ["Veuillez pivoter votre appareil<br>to&nbsp;landscape mode", "Gire su dispositivo<br>al modo horizontal"],
  ["to&nbsp;portrait mode", "al modo vertical"],
  ["to&nbsp;landscape mode", "al modo horizontal"],
  ["to portrait mode", "al modo vertical"],
  ["to landscape mode", "al modo horizontal"],
  ["Bien immobilier de prestige OFF MARKET à Marrakech", "Propiedad de prestigio OFF MARKET en Marrakech"],
];

const NO_OFF_PLAN_REPLACEMENTS: readonly Replacement[] = [
  ["Choisir la langue", "Velg språk"],
  ["Langue", "Språk"],
  ["<span>Sur plan</span>", "<span>Nybygg</span>"],
  ["Sur plan", "Nybygg"],
  ["Skip to main content", "Gå til hovedinnhold"],
  ["Aller au contenu principal", "Gå til hovedinnhold"],
  ["Accueil", "Hjem"],
  ["Navigation principale", "Hovednavigasjon"],
  ["Demander l'accès", "Be om tilgang"],
  ["Nous contacter", "Kontakt oss"],
  ["Immobilier privé à Marrakech", "Privat eiendom i Marrakech"],
  ["Marrakech, Maroc", "Marrakech, Marokko"],
  ["Marrakech, Morocco", "Marrakech, Marokko"],
  ["Accès privé sur demande", "Privat tilgang på forespørsel"],
  ["Tous droits réservés", "Alle rettigheter forbeholdt"],
  ["Confidentialité", "Personvern"],
  ["Privacy policy", "Personvern"],
  ["Mentions légales", "Juridisk merknad"],
  ["Recevoir les opportunités privées", "Motta private muligheter"],
  [
    "Soyez informé des nouveaux projets sélectionnés à Marrakech.",
    "Hold deg oppdatert om nye utvalgte prosjekter i Marrakech.",
  ],
  ["S'inscrire", "Meld deg på"],
  ["Simulateur", "Kalkulator"],
  ["Contact", "Kontakt"],
  ["Voir les détails du projet", "Se prosjektdetaljer"],
  ["LA SÉLECTION À PORTÉE DE MAIN", "UTVALGET INNEN REKKEVIDDE"],
  ["La sélection à portée de main", "Utvalget innen rekkevidde"],
  [
    "OFF MARKET sécurise chaque parcours jusqu'à la décision finale, avec un accompagnement clair et discret.",
    "OFF MARKET følger hver prosess frem til endelig beslutning, med tydelig og diskret veiledning.",
  ],
  [
    "OFF MARKET sécurise chaque parcours jusqu&rsquo;à la décision finale, avec un accompagnement clair et discret.",
    "OFF MARKET følger hver prosess frem til endelig beslutning, med tydelig og diskret veiledning.",
  ],
  [
    "OFF MARKET sécurise chaque parcours jusqu&amp;rsquo;à la décision finale, avec un accompagnement clair et discret.",
    "OFF MARKET følger hver prosess frem til endelig beslutning, med tydelig og diskret veiledning.",
  ],
  [
    "Nous accompagnons les échanges, les vérifications et la lecture stratégique de l&rsquo;opportunité.",
    "Vi følger dialogen, kontrollene og den strategiske vurderingen av muligheten.",
  ],
  [
    "Marrakech se révèle autrement selon l&rsquo;adresse : prestige central, rendement urbain, villas privées ou horizon patrimonial sur l&rsquo;Atlas.",
    "Marrakech viser seg forskjellig fra adresse til adresse: sentral prestisje, urban avkastning, private villaer eller langsiktig verdi mot Atlas.",
  ],
  ["Une méthode devient signature", "En metode blir en signatur"],
  ["Une méthode<br>\ndevient signature", "En metode<br>\nblir en signatur"],
  [
    "Des programmes sur plan sélectionnés pour leur architecture, leur emplacement et leur potentiel patrimonial à Marrakech.",
    "Nybyggprosjekter valgt for arkitektur, beliggenhet og langsiktig verdi i Marrakech.",
  ],
  [
    "Nous cadrons votre recherche, votre horizon, votre budget et votre logique d&rsquo;achat avec méthode et discrétion.",
    "Vi rammer inn søket, tidshorisonten, budsjettet og kjøpslogikken med metode og diskresjon.",
  ],
  [
    "Nous filtrons les biens selon leur adresse, leur potentiel, leur cohérence et leur niveau de confidentialité.",
    "Vi filtrerer eiendommer etter adresse, potensial, sammenheng og konfidensialitetsnivå.",
  ],
  ["Comprendre votre projet", "Forstå prosjektet ditt"],
  ["Cadrer votre recherche et votre horizon", "Ramme inn søket og horisonten"],
  ["Sélectionner les biens cohérents", "Velge eiendommer med sammenheng"],
  ["Négocier avec discrétion", "Forhandle diskret"],
  ["Négocier", "Forhandle"],
  ["Acquérir", "Kjøpe"],
  ["Appartements premium", "Premiumleiligheter"],
  ["Villas privéescious", "Private villaer"],
  ["Private villascious", "Private villaer"],
  ["Villas privéescious<br>\nSwimming Pool", "Private villaer<br>\nBasseng"],
  ["Villas privéescious Swimming Pool", "Private villaer Basseng"],
  ["Private villas", "Private villaer"],
  ["Stone Hammam", "Hammam i stein"],
  ["Beauty hammam", "Elegant hammam"],
  ["Center à grandes ouvertures", "Sentrum med store åpninger"],
  ["Center<br>\nà grandes ouvertures", "Sentrum<br>\nmed store åpninger"],
  ["Beauty</span>", "Elegant</span>"],
  [
    "Winding paths, paved with gray granite, resemble creeks and riverbeds that flow gently around OFF MARKET. White froth of hydrangeas and slender torsos of shadberries, suspended above invisible water, become a picturesque backdrop for a riverside walk.",
    "Slyngende stier i grå granitt følger vandringen rundt prosjektet. Vegetasjon, skygge og mineralske linjer skaper en rolig ramme for et diskret bomiljø.",
  ],
  [
    "Winding paths, paved with&nbsp;gray granite, resemble creeks and riverbeds that flow gently around&nbsp;OFF MARKET. White froth of&nbsp;hydrangeas and slender torsos of&nbsp;shadberries, suspended above&nbsp;invisible water, become a&nbsp;picturesque backdrop for&nbsp;a&nbsp;riverside walk.",
    "Slyngende stier i grå granitt følger vandringen rundt prosjektet. Vegetasjon, skygge og mineralske linjer skaper en rolig ramme for et diskret bomiljø.",
  ],
  ["OMBRES ET PERSPECTIVES", "SKYGGE OG PERSPEKTIV"],
  ["Ombres et perspectives", "Skygge og perspektiv"],
  ["COUR INTÉRIEURE", "INDRE GÅRDSROM"],
  ["Cour intérieure", "Indre gårdsrom"],
  ["JARDINS STRUCTURANTS", "STRUKTURERENDE HAGER"],
  ["Jardins structurants", "Strukturerende hager"],
  [
    "Une méthode d'acquisition en quatre étapes : comprendre, sélectionner, négocier, acquérir.",
    "En kjøpsmetode i fire steg: forstå, velge, forhandle og kjøpe.",
  ],
  [
    "Une méthode d&rsquo;acquisition en quatre étapes : comprendre, sélectionner, négocier, acquérir.",
    "En kjøpsmetode i fire steg: forstå, velge, forhandle og kjøpe.",
  ],
  [
    "OFF MARKET compose une sélection<br>\nof&nbsp;beautiful reality.",
    "OFF MARKET setter sammen et utvalg<br>\ntilpasset prosjektet ditt.",
  ],
  ["of beautiful reality", "tilpasset prosjektet ditt"],
  ["of&nbsp;beautiful reality", "tilpasset prosjektet ditt"],
  ["PERMANENT OUTDOOR RECREATION SPACES", "PERMANENTE UTEOMRÅDER"],
  ["VIDEO-MONITORED PLAYGROUNDS", "VIDEOOVERVÅKEDE LEKEOMRÅDER"],
  ["PORTABLE OUTDOOR FURNITURE", "FLEKSIBLE UTEMØBLER"],
  [
    "Route de l&rsquo;Ourika — villas, Atlas et horizon long terme.",
    "Route de l'Ourika — villaer, Atlas og langsiktig horisont.",
  ],
  ["À quelques minutes des adresses patrimoniales.", "Få minutter fra verdifulle adresser."],
  ["discrète Palmeraie", "Diskret Palmeraie"],
  ["PALETTE SOBRE OF BLOSSOMS", "NEDTONET GRØNN PALETT"],
  [
    "Agdal — adresses résidentielles modernes, jardins royaux à proximité et lecture patrimoniale claire.",
    "Agdal — moderne boligadresser, kongelige hager i nærheten og tydelig langsiktig verdi.",
  ],
  ["Panoramique Terraces", "Panoramaterrasser"],
  [
    "Des terrasses de vue où la lumière, la pierre et le jardin composent un cadre de vie discret et mémorable.",
    "Utsiktsterrasser der lys, stein og hage skaper en diskret og minneverdig ramme.",
  ],
  ["VOLUMES PATRIMONIAUX", "VARIGE VOLUMER"],
  ["Volumes patrimoniaux", "Varige volumer"],
  ["TRANSPARENT PANORAMIC RAILING", "TRANSPARENT PANORAMAREKKVERK"],
  ["Transparent panoramic railing", "Transparent panoramarekkverk"],
  ["LUMIÈRE MAÎTRISÉE", "KONTROLLERT LYS"],
  ["Lumière maîtrisée", "Kontrollert lys"],
  ["Parc-like Parcing", "Parklignende parkering"],
  [
    "Chaque détail est pensé avec exigence : volumes, matières et lumière au service d'une acquisition patrimoniale cohérente.",
    "Hver detalj er gjennomtenkt: volum, materialer og lys i tjeneste for et sammenhengende langsiktig kjøp.",
  ],
  [
    "Chaque détail est pensé avec exigence : volumes, matières et lumière au service d&rsquo;une acquisition patrimoniale cohérente.",
    "Hver detalj er gjennomtenkt: volum, materialer og lys i tjeneste for et sammenhengende langsiktig kjøp.",
  ],
  ["Intérieurs d&rsquo;exception", "Eksepsjonelle interiører"],
  ["Intérieurs d&amp;rsquo;exception", "Eksepsjonelle interiører"],
  ["Interieurs d exception", "Eksepsjonelle interiører"],
  ["Two levels", "To nivåer"],
  ["Investirissement", "Investering"],
  ["OASIS CONFIDENTIELLE AU CŒUR DE MARRAKECH", "KONFIDENSIELL OASE I HJERTET AV MARRAKECH"],
  ["OASIS CONFIDENTIELLE AU C&amp;OElig;UR DE MARRAKECH", "KONFIDENSIELL OASE I HJERTET AV MARRAKECH"],
  ["Adresses", "Adresser"],
  ["Intérieur", "Interiør"],
  ["Envoyer<br>\n                    une demande", "Send<br>\n                    en forespørsel"],
  ["Envoyer une demande", "Send en forespørsel"],
  [
    "Merci pour votre demande. Nous avons bien reçu votre message et vous recontacterons prochainement.",
    "Takk for forespørselen. Vi har mottatt meldingen og kontakter deg snart.",
  ],
  ["Demande", "Forespørsel"],
  ["Rappel", "Tilbakeringing"],
  ["Nom", "Navn"],
  ["Téléphone", "Telefon"],
  ["Envoyer la demande", "Send forespørsel"],
  ["En cliquant, vous acceptez notre", "Ved å klikke godtar du vår"],
  ["à notre", "vår"],
  ["politique de confidentialité", "personvernerklæring"],
  ["Sélection :", "Utvalg:"],
  ["Navigation fiche bien", "Navigasjon i eiendomsprofil"],
  ["Fermer la fiche", "Lukk eiendomsprofilen"],
  ["Plans transmis sur demande", "Plantegninger på forespørsel"],
  ["call time", "Tidspunkt for samtale"],
  ["Maison OFF MARKET", "OFF MARKET"],
  ["Veuillez pivoter votre appareil", "Roter enheten din"],
  ["Veuillez pivoter votre appareil<br>to&nbsp;portrait mode", "Roter enheten din<br>til stående format"],
  ["Veuillez pivoter votre appareil<br>to&nbsp;landscape mode", "Roter enheten din<br>til liggende format"],
  ["to&nbsp;portrait mode", "til stående format"],
  ["to&nbsp;landscape mode", "til liggende format"],
  ["to portrait mode", "til stående format"],
  ["to landscape mode", "til liggende format"],
  ["Bien immobilier de prestige OFF MARKET à Marrakech", "Prestisjeeiendom fra OFF MARKET i Marrakech"],
];

const ROUTE_REPLACEMENTS: Record<"en" | "es" | "it" | "nl" | "no", readonly Replacement[]> = {
  en: [
    ['href="/"', 'href="/en/"'],
    ['href="/about/"', 'href="/en/about/"'],
    ['href="/quartiers/"', 'href="/en/neighbourhoods/"'],
    ['href="/nos-projets/"', 'href="/en/projects/"'],
    ['href="/simulateur/"', 'href="/en/simulator/"'],
    ['href="/simulateur"', 'href="/en/simulator/"'],
    ['href="/sur-plan/"', 'href="/en/off-plan/"'],
    ['href="/sur-plan"', 'href="/en/off-plan/"'],
    ['href="/contact/"', 'href="/en/contact/"'],
    ['href="/contact"', 'href="/en/contact/"'],
    ['href="/off-market/"', 'href="/en/off-market/"'],
    ['href="/off-market"', 'href="/en/off-market/"'],
    ['href="/blog/"', 'href="/en/blog/"'],
    ['href="/blog"', 'href="/en/blog/"'],
    ['href="/privacy-policy/"', 'href="/en/privacy-policy/"'],
  ],
  es: [
    ['href="/"', 'href="/es/"'],
    ['href="/about/"', 'href="/es/sobre-nosotros/"'],
    ['href="/quartiers/"', 'href="/es/barrios/"'],
    ['href="/nos-projets/"', 'href="/es/proyectos/"'],
    ['href="/simulateur/"', 'href="/es/simulador/"'],
    ['href="/simulateur"', 'href="/es/simulador/"'],
    ['href="/sur-plan/"', 'href="/es/sobre-plano/"'],
    ['href="/sur-plan"', 'href="/es/sobre-plano/"'],
    ['href="/contact/"', 'href="/es/contacto/"'],
    ['href="/contact"', 'href="/es/contacto/"'],
    ['href="/off-market/"', 'href="/es/off-market/"'],
    ['href="/off-market"', 'href="/es/off-market/"'],
    ['href="/blog/"', 'href="/es/blog/"'],
    ['href="/blog"', 'href="/es/blog/"'],
    ['href="/privacy-policy/"', 'href="/es/politica-de-privacidad/"'],
    ['href="/en/"', 'href="/es/"'],
    ['href="/en/contact/"', 'href="/es/contacto/"'],
    ['href="/en/off-market/"', 'href="/es/off-market/"'],
    ['href="/en/off-plan/"', 'href="/es/sobre-plano/"'],
  ],
  nl: [
    ['href="/"', 'href="/nl/"'],
    ['href="/about/"', 'href="/nl/over-ons/"'],
    ['href="/quartiers/"', 'href="/nl/wijken/"'],
    ['href="/nos-projets/"', 'href="/nl/projecten/"'],
    ['href="/simulateur/"', 'href="/nl/simulator/"'],
    ['href="/simulateur"', 'href="/nl/simulator/"'],
    ['href="/sur-plan/"', 'href="/nl/nieuwbouw/"'],
    ['href="/sur-plan"', 'href="/nl/nieuwbouw/"'],
    ['href="/contact/"', 'href="/nl/contact/"'],
    ['href="/contact"', 'href="/nl/contact/"'],
    ['href="/off-market/"', 'href="/nl/off-market/"'],
    ['href="/off-market"', 'href="/nl/off-market/"'],
    ['href="/blog/"', 'href="/nl/blog/"'],
    ['href="/blog"', 'href="/nl/blog/"'],
    ['href="/privacy-policy/"', 'href="/nl/privacybeleid/"'],
    ['href="/en/"', 'href="/nl/"'],
    ['href="/en/contact/"', 'href="/nl/contact/"'],
    ['href="/en/off-market/"', 'href="/nl/off-market/"'],
    ['href="/en/off-plan/"', 'href="/nl/nieuwbouw/"'],
  ],
  it: [
    ['href="/"', 'href="/it/"'],
    ['href="/about/"', 'href="/it/chi-siamo/"'],
    ['href="/quartiers/"', 'href="/it/quartieri/"'],
    ['href="/nos-projets/"', 'href="/it/progetti/"'],
    ['href="/simulateur/"', 'href="/it/simulatore/"'],
    ['href="/simulateur"', 'href="/it/simulatore/"'],
    ['href="/sur-plan/"', 'href="/it/progetti-su-piano/"'],
    ['href="/sur-plan"', 'href="/it/progetti-su-piano/"'],
    ['href="/contact/"', 'href="/it/contatto/"'],
    ['href="/contact"', 'href="/it/contatto/"'],
    ['href="/off-market/"', 'href="/it/off-market/"'],
    ['href="/off-market"', 'href="/it/off-market/"'],
    ['href="/blog/"', 'href="/it/blog/"'],
    ['href="/blog"', 'href="/it/blog/"'],
    ['href="/privacy-policy/"', 'href="/it/privacy-policy/"'],
  ],
  no: [
    ['href="/"', 'href="/no/"'],
    ['href="/about/"', 'href="/no/om-oss/"'],
    ['href="/quartiers/"', 'href="/no/omrader/"'],
    ['href="/nos-projets/"', 'href="/no/prosjekter/"'],
    ['href="/simulateur/"', 'href="/no/kalkulator/"'],
    ['href="/simulateur"', 'href="/no/kalkulator/"'],
    ['href="/sur-plan/"', 'href="/no/nybygg/"'],
    ['href="/sur-plan"', 'href="/no/nybygg/"'],
    ['href="/contact/"', 'href="/no/kontakt/"'],
    ['href="/contact"', 'href="/no/kontakt/"'],
    ['href="/off-market/"', 'href="/no/off-market/"'],
    ['href="/off-market"', 'href="/no/off-market/"'],
    ['href="/blog/"', 'href="/no/blogg/"'],
    ['href="/blog"', 'href="/no/blogg/"'],
    ['href="/privacy-policy/"', 'href="/no/personvernerklaering/"'],
    ['href="/en/"', 'href="/no/"'],
    ['href="/en/contact/"', 'href="/no/kontakt/"'],
    ['href="/en/off-market/"', 'href="/no/off-market/"'],
    ['href="/en/off-plan/"', 'href="/no/nybygg/"'],
  ],
};

function replaceAllLiteral(value: string, from: string, to: string): string {
  return value.split(from).join(to);
}

function localizeHtml(html: string, replacements: readonly Replacement[]): string {
  const tokens = new Map<string, string>();
  let result = html;

  [...replacements]
    .sort((a, b) => b[0].length - a[0].length)
    .forEach(([from, to], index) => {
      const token = `\u0000OM_BUSINESS_LOC_${index}\u0000`;
      result = replaceAllLiteral(result, from, token);
      tokens.set(token, to);
    });

  tokens.forEach((to, token) => {
    result = replaceAllLiteral(result, token, to);
  });

  return result;
}

function localizeSegments(
  segments: BodySegment[],
  replacements: readonly Replacement[],
): BodySegment[] {
  return segments.map((segment) =>
    segment.kind === "html"
      ? { ...segment, html: localizeHtml(segment.html, replacements) }
      : segment,
  );
}

export function localizeBusinessLegacyContent(content: PageContent): PageContent {
  const locale = content.htmlLang as SiteLocale;
  const replacements =
    locale === "en"
      ? [...ROUTE_REPLACEMENTS.en, ...COMMON_OFF_PLAN_REPLACEMENTS, ...EN_OFF_PLAN_REPLACEMENTS]
      : locale === "es"
        ? [...ROUTE_REPLACEMENTS.es, ...COMMON_OFF_PLAN_REPLACEMENTS, ...ES_OFF_PLAN_REPLACEMENTS]
      : locale === "nl"
        ? [...ROUTE_REPLACEMENTS.nl, ...COMMON_OFF_PLAN_REPLACEMENTS, ...NL_OFF_PLAN_REPLACEMENTS]
        : locale === "it"
          ? [...ROUTE_REPLACEMENTS.it, ...IT_OFF_PLAN_REPLACEMENTS]
          : locale === "no"
            ? [...ROUTE_REPLACEMENTS.no, ...COMMON_OFF_PLAN_REPLACEMENTS, ...NO_OFF_PLAN_REPLACEMENTS]
            : [];

  if (!replacements.length) return content;

  return {
    ...content,
    bodySegments: localizeSegments(content.bodySegments, replacements).map((segment) => {
      if (segment.kind !== "html") return segment;
      if (locale === "nl") {
        return {
          ...segment,
          html: segment.html.replace(
            /(?:Door te klikken accepteert u onze|En cliquant, vous acceptez notre)\s*<br>\s*(?:onze|à notre)\s*(<a\b[^>]*>)\s*(?:politique de confidentialité|privacyverklaring)(\s*<\/a>)/gi,
            "Door te klikken, gaat u akkoord met ons<br>$1privacybeleid$2",
          ),
        };
      }
      if (locale !== "it") return segment;
      return {
        ...segment,
        html: segment.html.replace(/Marrakech,\s+Maroc\w*/g, "Marrakech, Marocco"),
      };
    }),
  };
}
