import type { BodySegment } from "@/lib/static-html/parsePage";
import type { SiteLocale } from "@/lib/i18n/types";

type Replacement = readonly [from: string, to: string];

const EN_REPLACEMENTS: readonly Replacement[] = [
  ["Langue", "Language"],
  ["Sur plan", "Off-plan"],
  ["Projet sur plan", "Off-plan project"],
  ["Villa sur plan", "Off-plan villa"],
  ["Private villascious", "Private villas"],
  ["Villas privéescious", "Private villas"],
  ["Villas privéescious<br>\nSwimming Pool", "Private villas<br>\nSwimming pool"],
  ["of beautiful reality", "that fits your project"],
  ["Parc-like Parcing", "Park-like parking"],
  ["Parc-like&nbsp;Parcing", "Park-like parking"],
  ["Investirissement", "Investment"],
  ["Aller au contenu principal", "Skip to main content"],
  ["L'immobilier privé à Marrakech", "Private real estate in Marrakech"],
  ["L'immobilier privé", "Private real estate"],
  [
    "Sélection immobilière privée à Marrakech",
    "Private real estate selection in Marrakech",
  ],
  [
    "Territoires d'investissement à Marrakech",
    "Investment areas in Marrakech",
  ],
  [
    "Villa sur plan à Marrakech — extérieur",
    "Off-plan villa in Marrakech — exterior",
  ],
  ["à Marrakech", "in Marrakech"],
  [
    "Accédez à une sélection confidentielle de villas, appartements et projets sur plan, étudiés selon les principes S.A.F.E. pour leur emplacement, leur sérieux, leur cohérence et leur potentiel.",
    "Access a confidential selection of villas, apartments and off-plan projects, reviewed with S.A.F.E. principles for their location, integrity, coherence and potential.",
  ],
  [
    "Accédez à une sélection confidentielle de villas, appartements et projets sur plan, étudiés selon les principes S.A.F.E pour leur emplacement, leur sérieux, leur cohérence et leur potentiel.",
    "Access a confidential selection of villas, apartments and off-plan projects, reviewed with S.A.F.E. principles for their location, integrity, coherence and potential.",
  ],
  [
    "Accédez à une sélection confidentielle de villas, appartements et opportunités sur plan, choisie pour son emplacement, sa rareté et sa cohérence d'investissement.",
    "Access a confidential selection of villas, apartments and off-plan opportunities, chosen for location, rarity and investment coherence.",
  ],
  ["Demander l'accès", "Request access"],
  ["Voir la sélection", "View the selection"],
  ["Principes S.A.F.E", "S.A.F.E. principles"],
  ["Lecture S.A.F.E", "S.A.F.E. review"],
  ["Projets étudiés avant présentation.", "Projects reviewed before presentation."],
  ["clients qualifiés accompagnés", "qualified clients supported"],
  ["Typologies suivies", "Tracked property types"],
  ["Villas privées", "Private villas"],
  ["Appartements Guéliz", "Guéliz apartments"],
  ["Riads de caractère", "Character riads"],
  ["Biens sur plan", "Off-plan properties"],
  ["Terrains rares", "Rare land"],
  ["Opportunités investisseur", "Investor opportunities"],
  ["QUI SOMMES-NOUS", "WHO WE ARE"],
  [
    "Une maison privée pour lire le marché immobilier de Marrakech avec exigence.",
    "A private house for reading the Marrakech property market with rigour.",
  ],
  [
    "OFF MARKET accompagne les acheteurs, investisseurs et propriétaires avec une sélection ciblée, une analyse claire et un accès discret aux opportunités pertinentes.",
    "OFF MARKET supports buyers, investors and owners with a targeted selection, clear analysis and discreet access to relevant opportunities.",
  ],
  ["Sélection ciblée", "Targeted selection"],
  ["Analyse claire", "Clear analysis"],
  ["Accompagnement discret", "Discreet guidance"],
  ["Découvrir notre approche", "Discover our approach"],
  ["QUARTIERS", "NEIGHBOURHOODS"],
  [
    "Les zones où se construisent les meilleures opportunités",
    "The districts where the finest opportunities take shape",
  ],
  ["Les zones où se construisent", "The districts where"],
  ["les meilleures opportunités", "the finest opportunities take shape"],
  [
    "Une sélection privée, révélée avec discrétion.",
    "A private selection, revealed with discretion.",
  ],
  [
    "Des biens rares, des adresses confidentielles et une lecture claire avant chaque décision.",
    "Rare properties, confidential addresses and a clear reading before every decision.",
  ],
  ["SIMULATEUR PRIVÉ", "PRIVATE SIMULATOR"],
  ["Simuler avant d'investir", "Simulate before investing"],
  [
    "Estimez le potentiel d'un bien à Marrakech selon votre usage, puis affinez les chiffres avec",
    "Estimate a Marrakech property's potential according to your use, then refine the figures with",
  ],
  ["Location courte durée", "Short-term rental"],
  ["Location longue durée", "Long-term rental"],
  ["Achat-revente", "Purchase-resale"],
  ["PARAMÈTRES", "PARAMETERS"],
  [
    "Ajustez vos hypothèses. Le résultat se recalcule en direct.",
    "Adjust your assumptions. The result recalculates live.",
  ],
  [
    "Estimation indicative. OFF MARKET affine cette simulation avec l'adresse exacte, les charges réelles et les biens disponibles.",
    "Indicative estimate. OFF MARKET refines this simulation with the exact address, actual charges and available properties.",
  ],
  ["Budget d'acquisition", "Purchase price"],
  ["Prix estimé du bien, hors frais.", "Estimated property price, excluding fees."],
  ["Prix nuitée moyen", "Average nightly rate"],
  ["Semaines d'usage personnel", "Weeks of personal use"],
  ["Taux d'occupation", "Occupancy rate"],
  ["Loyer mensuel estimé", "Monthly rent"],
  ["Horizon de revente", "Resale horizon"],
  ["Hypothèse de valorisation annuelle", "Annual appreciation assumption"],
  ["RÉSULTAT", "RESULT"],
  ["RENDEMENT BRUT ANNUEL", "GROSS ANNUAL YIELD"],
  [
    "avant charges, fiscalité et frais réels",
    "before charges, taxes and real operating costs",
  ],
  ["Recevoir une analyse privée", "Receive a private analysis"],
  ["Voir les biens compatibles", "View compatible properties"],
  ["LECTURES PRIVÉES", "PRIVATE READINGS"],
  ["Ce que nos clients viennent chercher", "What our clients are looking for"],
  ["Suivant", "Next"],
  [
    "Nous cherchions une opportunité claire, pas une liste de biens. OFF MARKET nous a aidés à comprendre l'adresse, la demande et le potentiel avant même la première visite.",
    "We were looking for a clear opportunity, not a property list. OFF MARKET helped us understand the address, demand and potential before the first visit.",
  ],
  [
    "Nous cherchions une opportunité claire, pas une liste de biens. OFF MARKET nous a aidés à comprendre l’adresse, la demande et le potentiel avant même la première visite.",
    "We were looking for a clear opportunity, not a property list. OFF MARKET helped us understand the address, demand and potential before the first visit.",
  ],
  [
    "La différence s’est faite dans la lecture du marché : comparables, risques, marge de négociation et cohérence patrimoniale. La décision est devenue beaucoup plus simple.",
    "The difference came from the market reading: comparables, risks, negotiation margin and long-term coherence. The decision became much simpler.",
  ],
  [
    "Nous avons apprécié la discrétion, le tri et la qualité des échanges. Les biens présentés étaient peu nombreux, mais réellement alignés avec notre projet.",
    "We appreciated the discretion, filtering and quality of the conversations. The properties shown were few, but genuinely aligned with our project.",
  ],
  ["Acheteur privé", "Private buyer"],
  ["Investisseur", "Investor"],
  ["Client accompagné", "Supported client"],
  ["Résidence secondaire · Marrakech", "Second home · Marrakech"],
  ["Appartement premium · Guéliz / Hivernage", "Premium apartment · Guéliz / Hivernage"],
  ["Riad de caractère · Médina", "Character riad · Medina"],
  ["ACCÈS PRIVÉ", "PRIVATE ACCESS"],
  ["Recevoir la sélection off-market", "Receive the off-market selection"],
  [
    "Remplissez le formulaire pour accéder aux projets confidentiels et recevoir une sélection privée adaptée à votre budget.",
    "Complete the form to access confidential projects and receive a private selection aligned with your budget.",
  ],
  ["Nom complet", "Full name"],
  ["Numéro de téléphone", "Phone number"],
  ["Indicatif pays", "Country code"],
  ["Numéro", "Number"],
  ["Sélectionnez votre budget", "Select your budget"],
  ["Message (optionnel)", "Message (optional)"],
  [
    "En cliquant sur le bouton, vous acceptez que OFF MARKET vous contacte au sujet de votre demande.",
    "By clicking the button, you agree that OFF MARKET may contact you about your request.",
  ],
  ["Confidentialité", "Privacy policy"],
  ["PARLONS-EN", "LET'S TALK"],
  ["Votre projet mérite une lecture privée.", "Your project deserves a private reading."],
  ["Dites-nous ce que vous recherchez.", "Tell us what you are looking for."],
  [
    "OFF MARKET vous répond avec une sélection ciblée, une analyse claire et un accompagnement discret.",
    "OFF MARKET will respond with a targeted selection, clear analysis and discreet guidance.",
  ],
  [
    " vous répond avec une sélection ciblée, une analyse claire et un accompagnement discret.",
    " will respond with a targeted selection, clear analysis and discreet guidance.",
  ],
  ["Demander un accès privé", "Request private access"],
  ["Parler à un conseiller", "Speak to an adviser"],
  ["Veuillez pivoter votre appareil", "Please rotate your device"],
  ["to portrait mode", "to portrait mode"],
  ["to landscape mode", "to landscape mode"],
  ["to portrait mode", "to portrait mode"],
  ["to landscape mode", "to landscape mode"],
  ["Maison OFF MARKET", "OFF MARKET"],
  ["OFF MARKET — page d&amp;rsquo;accueil", "OFF MARKET — home"],
  ["call time", "Call time"],
];

const NL_REPLACEMENTS: readonly Replacement[] = [
  ["Choisir la langue", "Taal kiezen"],
  ["Langue", "Taal"],
  ["Accueil", "Home"],
  ["Notre Histoire", "Ons verhaal"],
  ["Opportunités rares", "Zeldzame kansen"],
  ["projets privés suivis", "privéprojecten gevolgd"],
  ["PRIVATE TOEGANG", "PRIVÉTOEGANG"],
  ["PRIVATE ACCESS", "PRIVÉTOEGANG"],
  ["Demander l'accès", "Toegang aanvragen"],
  ["Biens privés", "Privéaanbod"],
  ["Immobilier privé à Marrakech", "Privévastgoed in Marrakech"],
  ["Sur plan", "Nieuwbouw"],
  ["Simulateur", "Simulator"],
  ["Notre Histoire", "Ons verhaal"],
  ["Projet sur plan", "Nieuwbouwproject"],
  ["Villa sur plan", "Nieuwbouwvilla"],
  ["Private villascious", "Private villa's"],
  ["Villas privéescious", "Private villa's"],
  ["Villas privéescious<br>\nSwimming Pool", "Private villa's<br>\nZwembad"],
  ["of beautiful reality", "die bij uw project past"],
  ["Parc-like Parcing", "Parkachtige parking"],
  ["Parc-like&nbsp;Parcing", "Parkachtige parking"],
  ["Investirissement", "Investering"],
  ["Skip to main content", "Naar hoofdinhoud"],
  ["Aller au contenu principal", "Naar hoofdinhoud"],
  ["L'immobilier privé à Marrakech", "Privévastgoed in Marrakech"],
  ["L'immobilier privé", "Privévastgoed"],
  [
    "Sélection immobilière privée à Marrakech",
    "Private vastgoedselectie in Marrakech",
  ],
  [
    "Territoires d'investissement à Marrakech",
    "Investeringsgebieden in Marrakech",
  ],
  [
    "Villa sur plan à Marrakech — extérieur",
    "Nieuwbouwvilla in Marrakech — exterieur",
  ],
  ["à Marrakech", "in Marrakech"],
  [
    "Accédez à une sélection confidentielle de villas, appartements et projets sur plan, étudiés selon les principes S.A.F.E. pour leur emplacement, leur sérieux, leur cohérence et leur potentiel.",
    "Krijg toegang tot een vertrouwelijke selectie van villa's, appartementen en nieuwbouwprojecten, beoordeeld volgens de S.A.F.E.-principes op locatie, betrouwbaarheid, samenhang en potentieel.",
  ],
  [
    "Accédez à une sélection confidentielle de villas, appartements et projets sur plan, étudiés selon les principes S.A.F.E pour leur emplacement, leur sérieux, leur cohérence et leur potentiel.",
    "Krijg toegang tot een vertrouwelijke selectie van villa's, appartementen en nieuwbouwprojecten, beoordeeld volgens de S.A.F.E.-principes op locatie, betrouwbaarheid, samenhang en potentieel.",
  ],
  [
    "Accédez à une sélection confidentielle de villas, appartements et opportunités sur plan, choisie pour son emplacement, sa rareté et sa cohérence d'investissement.",
    "Krijg toegang tot een vertrouwelijke selectie van villa's, appartementen en nieuwbouwkansen, gekozen om hun locatie, zeldzaamheid en investeringssamenhang.",
  ],
  ["Demander l'accès", "Toegang aanvragen"],
  ["Voir la sélection", "De selectie bekijken"],
  ["Principes S.A.F.E", "S.A.F.E.-principes"],
  ["Lecture S.A.F.E", "S.A.F.E.-analyse"],
  ["Projets étudiés avant présentation.", "Projecten geanalyseerd vóór presentatie."],
  ["clients qualifiés accompagnés", "gekwalificeerde klanten begeleid"],
  ["Typologies suivies", "Opgevolgde typologieën"],
  ["Villas privées", "Private villa's"],
  ["Appartements Guéliz", "Appartementen in Guéliz"],
  ["Riads de caractère", "Karaktervolle riads"],
  ["Biens sur plan", "Nieuwbouwvastgoed"],
  ["Terrains rares", "Zeldzame gronden"],
  ["Opportunités investisseur", "Investeringskansen"],
  ["QUI SOMMES-NOUS", "WIE WIJ ZIJN"],
  [
    "Une maison privée pour lire le marché immobilier de Marrakech avec exigence.",
    "Een privaat huis om de vastgoedmarkt van Marrakech met precisie te lezen.",
  ],
  [
    "OFF MARKET accompagne les acheteurs, investisseurs et propriétaires avec une sélection ciblée, une analyse claire et un accès discret aux opportunités pertinentes.",
    "OFF MARKET begeleidt kopers, investeerders en eigenaars met een gerichte selectie, heldere analyse en discrete toegang tot relevante kansen.",
  ],
  ["Sélection ciblée", "Gerichte selectie"],
  ["Analyse claire", "Heldere analyse"],
  ["Accompagnement discret", "Discrete begeleiding"],
  ["Découvrir notre approche", "Onze aanpak ontdekken"],
  ["QUARTIERS", "WIJKEN"],
  [
    "Les zones où se construisent les meilleures opportunités",
    "De zones waar de beste kansen ontstaan",
  ],
  ["Les zones où se construisent", "De zones waar"],
  ["les meilleures opportunités", "de beste kansen ontstaan"],
  [
    "Une sélection privée, révélée avec discrétion.",
    "Een private selectie, discreet onthuld.",
  ],
  [
    "Des biens rares, des adresses confidentielles et une lecture claire avant chaque décision.",
    "Zeldzaam vastgoed, vertrouwelijke adressen en een heldere analyse vóór elke beslissing.",
  ],
  ["SIMULATEUR PRIVÉ", "PRIVÉSIMULATOR"],
  ["Simuler avant d'investir", "Simuleren vóór u investeert"],
  [
    "Estimez le potentiel d'un bien à Marrakech selon votre usage, puis affinez les chiffres avec",
    "Schat het potentieel van een pand in Marrakech volgens uw gebruik en verfijn daarna de cijfers met",
  ],
  ["Location courte durée", "Korte termijn verhuur"],
  ["Location longue durée", "Lange termijn verhuur"],
  ["Achat-revente", "Aankoop en herverkoop"],
  ["PARAMÈTRES", "INSTELLINGEN"],
  [
    "Ajustez vos hypothèses. Le résultat se recalcule en direct.",
    "Pas uw aannames aan. Het resultaat wordt live herberekend.",
  ],
  [
    "Estimation indicative. OFF MARKET affine cette simulation avec l'adresse exacte, les charges réelles et les biens disponibles.",
    "Indicatieve schatting. OFF MARKET verfijnt deze simulatie met het exacte adres, de werkelijke kosten en beschikbare woningen.",
  ],
  ["Budget d'acquisition", "Aankoopprijs"],
  ["Prix estimé du bien, hors frais.", "Geschatte aankoopprijs, exclusief kosten."],
  ["Prix nuitée moyen", "Gemiddelde nachtprijs"],
  ["Semaines d'usage personnel", "Weken eigen gebruik"],
  ["Taux d'occupation", "Bezettingsgraad"],
  ["Loyer mensuel estimé", "Maandelijkse huur"],
  ["Horizon de revente", "Herverkoophorizon"],
  ["Hypothèse de valorisation annuelle", "Aanname jaarlijkse waardestijging"],
  ["RÉSULTAT", "RESULTAAT"],
  ["RENDEMENT BRUT ANNUEL", "BRUTO HUURRENDEMENT"],
  [
    "avant charges, fiscalité et frais réels",
    "vóór kosten, fiscaliteit en werkelijke lasten",
  ],
  ["Recevoir une analyse privée", "Een private analyse ontvangen"],
  ["Voir les biens compatibles", "Passend vastgoed bekijken"],
  ["LECTURES PRIVÉES", "PRIVATE ANALYSES"],
  ["Ce que nos clients viennent chercher", "Wat onze klanten komen zoeken"],
  ["Suivant", "Volgende"],
  [
    "Nous cherchions une opportunité claire, pas une liste de biens. OFF MARKET nous a aidés à comprendre l'adresse, la demande et le potentiel avant même la première visite.",
    "Wij zochten een duidelijke kans, geen lijst met panden. OFF MARKET hielp ons het adres, de vraag en het potentieel te begrijpen nog vóór het eerste bezoek.",
  ],
  [
    "Nous cherchions une opportunité claire, pas une liste de biens. OFF MARKET nous a aidés à comprendre l’adresse, la demande et le potentiel avant même la première visite.",
    "Wij zochten een duidelijke kans, geen lijst met panden. OFF MARKET hielp ons het adres, de vraag en het potentieel te begrijpen nog vóór het eerste bezoek.",
  ],
  [
    "La différence s’est faite dans la lecture du marché : comparables, risques, marge de négociation et cohérence patrimoniale. La décision est devenue beaucoup plus simple.",
    "Het verschil zat in de marktlezing: vergelijkbare panden, risico's, onderhandelingsruimte en patrimoniale samenhang. De beslissing werd veel eenvoudiger.",
  ],
  [
    "Nous avons apprécié la discrétion, le tri et la qualité des échanges. Les biens présentés étaient peu nombreux, mais réellement alignés avec notre projet.",
    "Wij waardeerden de discretie, de filtering en de kwaliteit van de gesprekken. Er werden weinig panden voorgesteld, maar ze sloten echt aan bij ons project.",
  ],
  ["Acheteur privé", "Private koper"],
  ["Investisseur", "Investeerder"],
  ["Client accompagné", "Begeleide klant"],
  ["Résidence secondaire · Marrakech", "Tweede verblijf · Marrakech"],
  ["Appartement premium · Guéliz / Hivernage", "Premium appartement · Guéliz / Hivernage"],
  ["Riad de caractère · Médina", "Karaktervolle riad · Medina"],
  ["ACCÈS PRIVÉ", "PRIVÉTOEGANG"],
  ["Recevoir la sélection off-market", "De off-market selectie ontvangen"],
  [
    "Remplissez le formulaire pour accéder aux projets confidentiels et recevoir une sélection privée adaptée à votre budget.",
    "Vul het formulier in om toegang te krijgen tot vertrouwelijke projecten en een private selectie te ontvangen die past bij uw budget.",
  ],
  ["Nom complet", "Volledige naam"],
  ["Numéro de téléphone", "Telefoonnummer"],
  ["Indicatif pays", "Landcode"],
  ["Numéro", "Nummer"],
  ["Sélectionnez votre budget", "Selecteer uw budget"],
  ["Message (optionnel)", "Bericht (optioneel)"],
  [
    "En cliquant sur le bouton, vous acceptez que OFF MARKET vous contacte au sujet de votre demande.",
    "Door op de knop te klikken, stemt u ermee in dat OFF MARKET contact met u opneemt over uw aanvraag.",
  ],
  ["Confidentialité", "Privacy"],
  ["Tous droits réservés", "Alle rechten voorbehouden"],
  ["Mentions légales", "Juridische vermeldingen"],
  ["politique de confidentialité", "privacybeleid"],
  ["Sélection :", "Selectie:"],
  ["Navigation fiche bien", "Navigatie vastgoedfiche"],
  ["Fermer la fiche", "Vastgoedfiche sluiten"],
  ["Plans transmis sur demande", "Plattegronden beschikbaar op aanvraag"],
  ["Rappel", "Terugbelverzoek"],
  ["PARLONS-EN", "LATEN WE PRATEN"],
  ["Votre projet mérite une lecture privée.", "Uw project verdient een private analyse."],
  ["Dites-nous ce que vous recherchez.", "Vertel ons wat u zoekt."],
  [
    "OFF MARKET vous répond avec une sélection ciblée, une analyse claire et un accompagnement discret.",
    "OFF MARKET antwoordt met een gerichte selectie, heldere analyse en discrete begeleiding.",
  ],
  [
    " vous répond avec une sélection ciblée, une analyse claire et un accompagnement discret.",
    " antwoordt met een gerichte selectie, heldere analyse en discrete begeleiding.",
  ],
  ["Demander un accès privé", "Private toegang aanvragen"],
  ["Simulateur", "Simulator"],
  ["Parler à un conseiller", "Met een adviseur spreken"],
  ["Veuillez pivoter votre appareil", "Draai uw apparaat"],
  ["to portrait mode", "naar portretmodus"],
  ["to landscape mode", "naar landschapsmodus"],
  ["to portrait mode", "naar portretmodus"],
  ["to landscape mode", "naar landschapsmodus"],
  ["Private properties", "Private panden"],
  ["Contact us", "Contact"],
  ["Our story", "Ons verhaal"],
  ["Off-plan", "Nieuwbouw"],
  ["Back to top", "Terug naar boven"],
  ["Private real estate in Marrakech", "Privévastgoed in Marrakech"],
  ["Choose language", "Taal kiezen"],
  ["Main navigation", "Hoofdnavigatie"],
  ["Maison OFF MARKET", "OFF MARKET"],
  ["Sélection privée d'opportunités immobilières à Marrakech.", "Private selectie van vastgoedkansen in Marrakech."],
  ["OFF MARKET — page d&amp;rsquo;accueil", "OFF MARKET — startpagina"],
  ["call time", "Tijdstip gesprek"],
  ["Envoyer<br>\n                    une demande", "Een aanvraag verzenden"],
];

const IT_REPLACEMENTS: readonly Replacement[] = [
  ["Choisir la langue", "Scegli la lingua"],
  ["Langue", "Lingua"],
  ["Aller au contenu principal", "Vai al contenuto principale"],
  ["L'immobilier privé à Marrakech", "L'immobiliare privato a Marrakech"],
  ["L'immobilier privé", "L'immobiliare privato"],
  [
    "Sélection immobilière privée à Marrakech",
    "Selezione immobiliare privata a Marrakech",
  ],
  [
    "Territoires d'investissement à Marrakech",
    "Zone di investimento a Marrakech",
  ],
  [
    "Villa sur plan à Marrakech — extérieur",
    "Villa su progetto a Marrakech — esterno",
  ],
  ["à Marrakech", "a Marrakech"],
  [
    "Accédez à une sélection confidentielle de villas, appartements et projets sur plan, étudiés selon les principes S.A.F.E. pour leur emplacement, leur sérieux, leur cohérence et leur potentiel.",
    "Accedi a una selezione riservata di ville, appartamenti e progetti in costruzione, valutati secondo i principi S.A.F.E. per posizione, affidabilità, coerenza e potenziale.",
  ],
  [
    "Accédez à une sélection confidentielle de villas, appartements et projets sur plan, étudiés selon les principes S.A.F.E pour leur emplacement, leur sérieux, leur cohérence et leur potentiel.",
    "Accedi a una selezione riservata di ville, appartamenti e progetti in costruzione, valutati secondo i principi S.A.F.E. per posizione, affidabilità, coerenza e potenziale.",
  ],
  [
    "Accédez à une sélection confidentielle de villas, appartements et opportunités sur plan, choisie pour son emplacement, sa rareté et sa cohérence d'investissement.",
    "Accedi a una selezione riservata di ville, appartamenti e opportunità in costruzione, scelta per posizione, rarità e coerenza dell’investimento.",
  ],
  ["Demander l'accès", "Richiedi l'accesso"],
  ["Voir la sélection", "Vedi la selezione"],
  ["Principes S.A.F.E", "Principi S.A.F.E."],
  ["Lecture S.A.F.E", "Analisi S.A.F.E."],
  ["Projets étudiés avant présentation.", "Progetti esaminati prima della presentazione."],
  ["clients qualifiés accompagnés", "clienti qualificati accompagnati"],
  ["Typologies suivies", "Tipologie seguite"],
  ["Villas privées", "Ville private"],
  ["Appartements Guéliz", "Appartamenti a Guéliz"],
  ["Riads de caractère", "Riad di carattere"],
  ["Biens sur plan", "Immobili in costruzione"],
  ["Terrains rares", "Terreni rari"],
  ["Opportunités investisseur", "Opportunità per investitori"],
  ["QUI SOMMES-NOUS", "CHI SIAMO"],
  [
    "Une maison privée pour lire le marché immobilier de Marrakech avec exigence.",
    "Una maison privata per leggere il mercato immobiliare di Marrakech con rigore.",
  ],
  [
    "OFF MARKET accompagne les acheteurs, investisseurs et propriétaires avec une sélection ciblée, une analyse claire et un accès discret aux opportunités pertinentes.",
    "OFF MARKET accompagna acquirenti, investitori e proprietari con una selezione mirata, un’analisi chiara e un accesso discreto alle opportunità pertinenti.",
  ],
  ["Sélection ciblée", "Selezione mirata"],
  ["Analyse claire", "Analisi chiara"],
  ["Accompagnement discret", "Accompagnamento discreto"],
  ["Découvrir notre approche", "Scopri il nostro approccio"],
  ["QUARTIERS", "QUARTIERI"],
  [
    "Les zones où se construisent les meilleures opportunités",
    "Le zone in cui nascono le migliori opportunità",
  ],
  ["Les zones où se construisent", "Le zone in cui nascono"],
  ["les meilleures opportunités", "le migliori opportunità"],
  ["Une sélection privée, révélée avec discrétion.", "Una selezione privata, rivelata con discrezione."],
  [
    "Des biens rares, des adresses confidentielles et une lecture claire avant chaque décision.",
    "Immobili rari, indirizzi riservati e una lettura chiara prima di ogni decisione.",
  ],
  ["SIMULATEUR PRIVÉ", "SIMULATORE PRIVATO"],
  ["Simuler avant d'investir", "Simula prima di investire"],
  [
    "Estimez le potentiel d'un bien à Marrakech selon votre usage, puis affinez les chiffres avec",
    "Stima il potenziale di un immobile a Marrakech in base al tuo utilizzo, poi affina i numeri con",
  ],
  ["Location courte durée", "Affitto a breve termine"],
  ["Location longue durée", "Affitto a lungo termine"],
  ["Achat-revente", "Acquisto e rivendita"],
  ["PARAMÈTRES", "PARAMETRI"],
  ["Ajustez vos hypothèses. Le résultat se recalcule en direct.", "Regola le tue ipotesi. Il risultato si ricalcola in tempo reale."],
  [
    "Estimation indicative. OFF MARKET affine cette simulation avec l'adresse exacte, les charges réelles et les biens disponibles.",
    "Stima indicativa. OFF MARKET perfeziona questa simulazione con l’indirizzo esatto, i costi reali e gli immobili disponibili.",
  ],
  ["Budget d'acquisition", "Budget di acquisto"],
  ["Prix estimé du bien, hors frais.", "Prezzo stimato dell’immobile, escluse le spese."],
  ["Prix nuitée moyen", "Prezzo medio per notte"],
  ["Semaines d'usage personnel", "Settimane di uso personale"],
  ["Taux d'occupation", "Tasso di occupazione"],
  ["Loyer mensuel estimé", "Canone mensile stimato"],
  ["Horizon de revente", "Orizzonte di rivendita"],
  ["Hypothèse de valorisation annuelle", "Ipotesi di rivalutazione annua"],
  ["RÉSULTAT", "RISULTATO"],
  ["RENDEMENT BRUT ANNUEL", "RENDIMENTO LORDO ANNUO"],
  ["avant charges, fiscalité et frais réels", "prima di costi, imposte e spese operative reali"],
  ["Recevoir une analyse privée", "Ricevi un’analisi privata"],
  ["Voir les biens compatibles", "Vedi gli immobili compatibili"],
  ["LECTURES PRIVÉES", "LETTURE PRIVATE"],
  ["Ce que nos clients viennent chercher", "Cosa cercano i nostri clienti"],
  ["Afficher le témoignage suivant", "Mostra la testimonianza successiva"],
  ["Suivant", "Successiva"],
  [
    "Nous cherchions une opportunité claire, pas une liste de biens. OFF MARKET nous a aidés à comprendre l'adresse, la demande et le potentiel avant même la première visite.",
    "Cercavamo un’opportunità chiara, non un elenco di immobili. OFF MARKET ci ha aiutati a comprendere l’indirizzo, la domanda e il potenziale prima ancora della prima visita.",
  ],
  [
    "Nous cherchions une opportunité claire, pas une liste de biens. OFF MARKET nous a aidés à comprendre l’adresse, la demande et le potentiel avant même la première visite.",
    "Cercavamo un’opportunità chiara, non un elenco di immobili. OFF MARKET ci ha aiutati a comprendere l’indirizzo, la domanda e il potenziale prima ancora della prima visita.",
  ],
  [
    "La différence s’est faite dans la lecture du marché : comparables, risques, marge de négociation et cohérence patrimoniale. La décision est devenue beaucoup plus simple.",
    "La differenza è stata nella lettura del mercato: comparabili, rischi, margine di negoziazione e coerenza patrimoniale. La decisione è diventata molto più semplice.",
  ],
  [
    "Nous avons apprécié la discrétion, le tri et la qualité des échanges. Les biens présentés étaient peu nombreux, mais réellement alignés avec notre projet.",
    "Abbiamo apprezzato la discrezione, la selezione e la qualità degli scambi. Gli immobili presentati erano pochi, ma realmente in linea con il nostro progetto.",
  ],
  ["Acheteur privé", "Acquirente privato"],
  ["Investisseur", "Investitore"],
  ["Client accompagné", "Cliente accompagnato"],
  ["Résidence secondaire · Marrakech", "Seconda casa · Marrakech"],
  ["Appartement premium · Guéliz / Hivernage", "Appartamento premium · Guéliz / Hivernage"],
  ["Riad de caractère · Médina", "Riad di carattere · Medina"],
  ["ACCÈS PRIVÉ", "ACCESSO PRIVATO"],
  ["Recevoir la sélection off-market", "Ricevi la selezione off-market"],
  ["Remplissez le formulaire pour accéder aux projets confidentiels et recevoir une sélection privée adaptée à votre budget.", "Compila il modulo per accedere ai progetti riservati e ricevere una selezione privata adatta al tuo budget."],
  ["Nom complet", "Nome completo"],
  ["Numéro de téléphone", "Numero di telefono"],
  ["Indicatif pays", "Prefisso internazionale"],
  ["Numéro", "Numero"],
  ["Sélectionnez votre budget", "Seleziona il tuo budget"],
  ["Message (optionnel)", "Messaggio (facoltativo)"],
  ["En cliquant sur le bouton, vous acceptez que OFF MARKET vous contacte au sujet de votre demande.", "Cliccando sul pulsante, accetti di essere contattato da OFF MARKET in merito alla tua richiesta."],
  ["Confidentialité", "Privacy"],
  ["PARLONS-EN", "PARLIAMONE"],
  ["Votre projet mérite une lecture privée.", "Il tuo progetto merita un’analisi privata."],
  ["Dites-nous ce que vous recherchez.", "Raccontaci cosa stai cercando."],
  ["OFF MARKET vous répond avec une sélection ciblée, une analyse claire et un accompagnement discret.", "OFF MARKET ti risponderà con una selezione mirata, un’analisi chiara e un accompagnamento discreto."],
  ["Demander un accès privé", "Richiedi un accesso privato"],
  ["Parler à un conseiller", "Parla con un consulente"],
  ["Slide precedente", "Slide precedente"],
  ["Slide suivante", "Slide successiva"],
  ["Général", "Generale"],
  ["À propos", "Informazioni"],
  ["Caractéristiques", "Caratteristiche"],
  ["Extérieur", "Esterno"],
  ["Intérieur", "Interno"],
  ["Rez-de-chaussée", "Piano terra"],
  ["Étage", "Primo piano"],
  ["Salles d'eau", "Bagni"],
  ["Détails sur demande", "Dettagli su richiesta"],
  ["Prix", "Prezzo"],
  ["À partir de 351 000 €", "Da 351.000 €"],
  ["Rappel", "Richiamami"],
  ["Recevoir le dossier", "Ricevi il dossier"],
  ["Plans & configuration", "Planimetrie e configurazione"],
  ["Navigation fiche bien", "Navigazione scheda immobile"],
  ["Skip to main content", "Vai al contenuto principale"],
  ["Private properties", "Immobili privati"],
  ["Contact us", "Contattaci"],
  ["Off-plan", "In costruzione"],
  ["Simulator", "Simulatore"],
  ["Request access", "Richiedi l'accesso"],
  ["Private real estate in Marrakech", "Immobiliare privato a Marrakech"],
  ["Maison OFF MARKET", "OFF MARKET"],
  ["une demande", "una richiesta"],
  ["Maroccocococo", "Marocco"],
  ["Maroccoco", "Marocco"],
  ["to portrait mode", "in modalità verticale"],
  ["to landscape mode", "in modalità orizzontale"],
  ["to portrait mode", "in modalità verticale"],
  ["to landscape mode", "in modalità orizzontale"],
  ["Nomeeeee completo", "Nome completo"],
  ["Nomeeee", "Nome"],
  ["call time", "Orario della chiamata"],
  ["Envoyer<br>\n                    une demande", "Invia una richiesta"],
  ["OFF MARKET — page d&amp;rsquo;accueil", "OFF MARKET — home"],
  ["data-lang=\"FR\">FR", "data-lang=\"IT\">IT"],
  ["su piano", "in costruzione"],
  ["Bien immobilier de prestige OFF MARKET a Marrakech", "Immobiliare di prestigio OFF MARKET a Marrakech"],
  ["Richiestar un appel", "Richiedi un contatto"],
  ["Planimetrie &amp; configuration", "Planimetrie e configurazione"],
  ["Slide suivante", "Slide successiva"],
  ["5 photos", "5 foto"],
  ["Maroccocococo", "Marocco"],
];

const ES_REPLACEMENTS: readonly Replacement[] = [
  ["Choisir la langue", "Elegir idioma"],
  ["Langue", "Idioma"],
  ["Accueil", "Inicio"],
  ["Notre Histoire", "Nuestra historia"],
  ["Opportunités rares", "Oportunidades raras"],
  ["projets privés suivis", "proyectos privados acompañados"],
  ["PRIVATE TOEGANG", "ACCESO PRIVADO"],
  ["PRIVATE ACCESS", "ACCESO PRIVADO"],
  ["Demander l'accès", "Solicitar acceso"],
  ["Biens privés", "Propiedades privadas"],
  ["Immobilier privé à Marrakech", "Inmobiliaria privada en Marrakech"],
  ["Sur plan", "Sobre plano"],
  ["Simulateur", "Simulador"],
  ["Projet sur plan", "Proyecto sobre plano"],
  ["Villa sur plan", "Villa sobre plano"],
  ["Private villascious", "Villas privadas"],
  ["Villas privéescious", "Villas privadas"],
  ["Villas privéescious<br>\nSwimming Pool", "Villas privadas<br>\nPiscina"],
  ["of beautiful reality", "adaptada a su proyecto"],
  ["of&nbsp;beautiful reality", "adaptada a su proyecto"],
  ["Parc-like Parcing", "Aparcamiento tipo parque"],
  ["Parc-like&nbsp;Parcing", "Aparcamiento tipo parque"],
  ["Investirissement", "Inversión"],
  ["Skip to main content", "Saltar al contenido principal"],
  ["Aller au contenu principal", "Saltar al contenido principal"],
  ["L'immobilier privé à Marrakech", "Inmobiliaria privada en Marrakech"],
  ["L'immobilier privé", "Inmobiliaria privada"],
  [
    "Sélection immobilière privée à Marrakech",
    "Selección inmobiliaria privada en Marrakech",
  ],
  [
    "Territoires d'investissement à Marrakech",
    "Zonas de inversión en Marrakech",
  ],
  [
    "Villa sur plan à Marrakech — extérieur",
    "Villa sobre plano en Marrakech — exterior",
  ],
  ["à Marrakech", "en Marrakech"],
  [
    "Accédez à une sélection confidentielle de villas, appartements et projets sur plan, étudiés selon les principes S.A.F.E. pour leur emplacement, leur sérieux, leur cohérence et leur potentiel.",
    "Acceda a una selección confidencial de villas, apartamentos y proyectos sobre plano, analizados según los principios S.A.F.E. por su ubicación, solidez, coherencia y potencial.",
  ],
  [
    "Accédez à une sélection confidentielle de villas, appartements et projets sur plan, étudiés selon les principes S.A.F.E pour leur emplacement, leur sérieux, leur cohérence et leur potentiel.",
    "Acceda a una selección confidencial de villas, apartamentos y proyectos sobre plano, analizados según los principios S.A.F.E. por su ubicación, solidez, coherencia y potencial.",
  ],
  [
    "Accédez à une sélection confidentielle de villas, appartements et opportunités sur plan, choisie pour son emplacement, sa rareté et sa cohérence d'investissement.",
    "Acceda a una selección confidencial de villas, apartamentos y oportunidades sobre plano, elegida por su ubicación, rareza y coherencia de inversión.",
  ],
  ["Voir la sélection", "Ver la selección"],
  ["Principes S.A.F.E", "Principios S.A.F.E."],
  ["Lecture S.A.F.E", "Análisis S.A.F.E."],
  ["Projets étudiés avant présentation.", "Proyectos analizados antes de su presentación."],
  ["clients qualifiés accompagnés", "clientes cualificados acompañados"],
  ["Typologies suivies", "Tipologías acompañadas"],
  ["Villas privées", "Villas privadas"],
  ["Appartements Guéliz", "Apartamentos en Guéliz"],
  ["Riads de caractère", "Riads con carácter"],
  ["Biens sur plan", "Propiedades sobre plano"],
  ["Terrains rares", "Terrenos raros"],
  ["Opportunités investisseur", "Oportunidades para inversores"],
  ["QUI SOMMES-NOUS", "QUIÉNES SOMOS"],
  [
    "Une maison privée pour lire le marché immobilier de Marrakech avec exigence.",
    "Una casa privada para leer el mercado inmobiliario de Marrakech con rigor.",
  ],
  [
    "OFF MARKET accompagne les acheteurs, investisseurs et propriétaires avec une sélection ciblée, une analyse claire et un accès discret aux opportunités pertinentes.",
    "OFF MARKET acompaña a compradores, inversores y propietarios con una selección precisa, un análisis claro y acceso discreto a oportunidades pertinentes.",
  ],
  ["Sélection ciblée", "Selección precisa"],
  ["Analyse claire", "Análisis claro"],
  ["Accompagnement discret", "Acompañamiento discreto"],
  ["Découvrir notre approche", "Descubrir nuestro enfoque"],
  ["QUARTIERS", "BARRIOS"],
  [
    "Les zones où se construisent les meilleures opportunités",
    "Las zonas donde se construyen las mejores oportunidades",
  ],
  ["Les zones où se construisent", "Las zonas donde nacen"],
  ["les meilleures opportunités", "las mejores oportunidades"],
  [
    "Une sélection privée, révélée avec discrétion.",
    "Una selección privada, revelada con discreción.",
  ],
  [
    "Des biens rares, des adresses confidentielles et une lecture claire avant chaque décision.",
    "Propiedades raras, direcciones confidenciales y una lectura clara antes de cada decisión.",
  ],
  ["SIMULATEUR PRIVÉ", "SIMULADOR PRIVADO"],
  ["Simuler avant d'investir", "Simular antes de invertir"],
  [
    "Estimez le potentiel d'un bien à Marrakech selon votre usage, puis affinez les chiffres avec",
    "Estime el potencial de una propiedad en Marrakech según su uso y luego refine las cifras con",
  ],
  ["Location courte durée", "Alquiler de corta estancia"],
  ["Location longue durée", "Alquiler de larga duración"],
  ["Achat-revente", "Compra y reventa"],
  ["PARAMÈTRES", "PARÁMETROS"],
  [
    "Ajustez vos hypothèses. Le résultat se recalcule en direct.",
    "Ajuste sus hipótesis. El resultado se recalcula en tiempo real.",
  ],
  [
    "Estimation indicative. OFF MARKET affine cette simulation avec l'adresse exacte, les charges réelles et les biens disponibles.",
    "Estimación orientativa. OFF MARKET afina esta simulación con la dirección exacta, los gastos reales y las propiedades disponibles.",
  ],
  ["Budget d'acquisition", "Presupuesto de adquisición"],
  ["Prix estimé du bien, hors frais.", "Precio estimado de la propiedad, sin gastos."],
  ["Prix nuitée moyen", "Precio medio por noche"],
  ["Semaines d'usage personnel", "Semanas de uso personal"],
  ["Taux d'occupation", "Tasa de ocupación"],
  ["Loyer mensuel estimé", "Renta mensual estimada"],
  ["Horizon de revente", "Horizonte de reventa"],
  ["Hypothèse de valorisation annuelle", "Hipótesis de revalorización anual"],
  ["RÉSULTAT", "RESULTADO"],
  ["RENDEMENT BRUT ANNUEL", "RENTABILIDAD BRUTA ANUAL"],
  [
    "avant charges, fiscalité et frais réels",
    "antes de gastos, fiscalidad y costes reales",
  ],
  ["Recevoir une analyse privée", "Recibir un análisis privado"],
  ["Voir les biens compatibles", "Ver propiedades compatibles"],
  ["LECTURES PRIVÉES", "LECTURAS PRIVADAS"],
  ["Ce que nos clients viennent chercher", "Lo que buscan nuestros clientes"],
  ["Afficher le témoignage suivant", "Mostrar el testimonio siguiente"],
  ["Suivant", "Siguiente"],
  [
    "Nous cherchions une opportunité claire, pas une liste de biens. OFF MARKET nous a aidés à comprendre l'adresse, la demande et le potentiel avant même la première visite.",
    "Buscábamos una oportunidad clara, no una lista de propiedades. OFF MARKET nos ayudó a entender la dirección, la demanda y el potencial incluso antes de la primera visita.",
  ],
  [
    "Nous cherchions une opportunité claire, pas une liste de biens. OFF MARKET nous a aidés à comprendre l’adresse, la demande et le potentiel avant même la première visite.",
    "Buscábamos una oportunidad clara, no una lista de propiedades. OFF MARKET nos ayudó a entender la dirección, la demanda y el potencial incluso antes de la primera visita.",
  ],
  [
    "La différence s’est faite dans la lecture du marché : comparables, risques, marge de négociation et cohérence patrimoniale. La décision est devenue beaucoup plus simple.",
    "La diferencia estuvo en la lectura del mercado: comparables, riesgos, margen de negociación y coherencia patrimonial. La decisión se volvió mucho más sencilla.",
  ],
  [
    "Nous avons apprécié la discrétion, le tri et la qualité des échanges. Les biens présentés étaient peu nombreux, mais réellement alignés avec notre projet.",
    "Apreciamos la discreción, el filtro y la calidad de los intercambios. Las propiedades presentadas eran pocas, pero realmente alineadas con nuestro proyecto.",
  ],
  ["Acheteur privé", "Comprador privado"],
  ["Investisseur", "Inversor"],
  ["Client accompagné", "Cliente acompañado"],
  ["Résidence secondaire · Marrakech", "Segunda residencia · Marrakech"],
  ["Appartement premium · Guéliz / Hivernage", "Apartamento premium · Guéliz / Hivernage"],
  ["Riad de caractère · Médina", "Riad con carácter · Medina"],
  ["ACCÈS PRIVÉ", "ACCESO PRIVADO"],
  ["Recevoir la sélection off-market", "Recibir la selección off-market"],
  [
    "Remplissez le formulaire pour accéder aux projets confidentiels et recevoir une sélection privée adaptée à votre budget.",
    "Complete el formulario para acceder a proyectos confidenciales y recibir una selección privada adaptada a su presupuesto.",
  ],
  ["Nom complet", "Nombre completo"],
  ["Numéro de téléphone", "Número de teléfono"],
  ["Indicatif pays", "Prefijo del país"],
  ["Numéro", "Número"],
  ["Sélectionnez votre budget", "Seleccione su presupuesto"],
  ["Message (optionnel)", "Mensaje (opcional)"],
  [
    "En cliquant sur le bouton, vous acceptez que OFF MARKET vous contacte au sujet de votre demande.",
    "Al hacer clic en el botón, acepta que OFF MARKET se ponga en contacto con usted en relación con su solicitud.",
  ],
  ["Confidentialité", "Privacidad"],
  ["Tous droits réservés", "Todos los derechos reservados"],
  ["Mentions légales", "Aviso legal"],
  ["politique de confidentialité", "política de privacidad"],
  ["Sélection :", "Selección:"],
  ["Navigation fiche bien", "Navegación de la ficha de propiedad"],
  ["Fermer la fiche", "Cerrar la ficha"],
  ["Plans transmis sur demande", "Planos disponibles previa solicitud"],
  ["Rappel", "Llamada"],
  ["PARLONS-EN", "HABLEMOS"],
  ["Votre projet mérite une lecture privée.", "Su proyecto merece una lectura privada."],
  ["Dites-nous ce que vous recherchez.", "Cuéntenos qué está buscando."],
  [
    "OFF MARKET vous répond avec une sélection ciblée, une analyse claire et un accompagnement discret.",
    "OFF MARKET le responde con una selección precisa, un análisis claro y un acompañamiento discreto.",
  ],
  [
    " vous répond avec une sélection ciblée, une analyse claire et un accompagnement discret.",
    " le responde con una selección precisa, un análisis claro y un acompañamiento discreto.",
  ],
  ["Demander un accès privé", "Solicitar acceso privado"],
  ["Parler à un conseiller", "Hablar con un asesor"],
  ["Veuillez pivoter votre appareil", "Gire su dispositivo"],
  ["to portrait mode", "al modo vertical"],
  ["to landscape mode", "al modo horizontal"],
  ["to&nbsp;portrait mode", "al modo vertical"],
  ["to&nbsp;landscape mode", "al modo horizontal"],
  ["to portrait mode", "al modo vertical"],
  ["to landscape mode", "al modo horizontal"],
  ["Private properties", "Propiedades privadas"],
  ["Contact us", "Contacto"],
  ["Our story", "Nuestra historia"],
  ["Off-plan", "Sobre plano"],
  ["Back to top", "Volver arriba"],
  ["Private real estate in Marrakech", "Inmobiliaria privada en Marrakech"],
  ["Choose language", "Elegir idioma"],
  ["Main navigation", "Navegación principal"],
  ["Maison OFF MARKET", "OFF MARKET"],
  ["Sélection privée d'opportunités immobilières à Marrakech.", "Selección privada de oportunidades inmobiliarias en Marrakech."],
  ["OFF MARKET — page d&amp;rsquo;accueil", "OFF MARKET — inicio"],
  ["call time", "Hora de llamada"],
  ["Envoyer<br>\n                    une demande", "Enviar<br>\n                    una solicitud"],
  ["Envoyer une demande", "Enviar una solicitud"],
];

const NO_REPLACEMENTS: readonly Replacement[] = [
  ["Choisir la langue", "Velg språk"],
  ["Langue", "Språk"],
  ["Accueil", "Hjem"],
  ["Notre Histoire", "Vår historie"],
  ["Opportunités rares", "Sjeldne muligheter"],
  ["projets privés suivis", "private prosjekter fulgt opp"],
  ["PRIVATE TOEGANG", "PRIVAT TILGANG"],
  ["PRIVATE ACCESS", "PRIVAT TILGANG"],
  ["Demander l'accès", "Be om tilgang"],
  ["Biens privés", "Private eiendommer"],
  ["Immobilier privé à Marrakech", "Privat eiendom i Marrakech"],
  ["Sur plan", "Nybygg"],
  ["Simulateur", "Kalkulator"],
  ["Projet sur plan", "Nybyggprosjekt"],
  ["Villa sur plan", "Nybyggvilla"],
  ["Private villascious", "Private villaer"],
  ["Villas privéescious", "Private villaer"],
  ["Villas privéescious<br>\nSwimming Pool", "Private villaer<br>\nBasseng"],
  ["of beautiful reality", "tilpasset prosjektet ditt"],
  ["of&nbsp;beautiful reality", "tilpasset prosjektet ditt"],
  ["Parc-like Parcing", "Parklignende parkering"],
  ["Parc-like&nbsp;Parcing", "Parklignende parkering"],
  ["Investirissement", "Investering"],
  ["Skip to main content", "Gå til hovedinnhold"],
  ["Aller au contenu principal", "Gå til hovedinnhold"],
  ["L'immobilier privé à Marrakech", "Privat eiendom i Marrakech"],
  ["L'immobilier privé", "Privat eiendom"],
  [
    "Sélection immobilière privée à Marrakech",
    "Privat eiendomsutvalg i Marrakech",
  ],
  [
    "Territoires d'investissement à Marrakech",
    "Investeringsområder i Marrakech",
  ],
  [
    "Villa sur plan à Marrakech — extérieur",
    "Nybyggvilla i Marrakech — eksteriør",
  ],
  ["à Marrakech", "i Marrakech"],
  [
    "Accédez à une sélection confidentielle de villas, appartements et projets sur plan, étudiés selon les principes S.A.F.E. pour leur emplacement, leur sérieux, leur cohérence et leur potentiel.",
    "Få tilgang til et konfidensielt utvalg av villaer, leiligheter og nybyggprosjekter, vurdert etter S.A.F.E.-prinsippene for beliggenhet, seriøsitet, sammenheng og potensial.",
  ],
  [
    "Accédez à une sélection confidentielle de villas, appartements et projets sur plan, étudiés selon les principes S.A.F.E pour leur emplacement, leur sérieux, leur cohérence et leur potentiel.",
    "Få tilgang til et konfidensielt utvalg av villaer, leiligheter og nybyggprosjekter, vurdert etter S.A.F.E.-prinsippene for beliggenhet, seriøsitet, sammenheng og potensial.",
  ],
  [
    "Accédez à une sélection confidentielle de villas, appartements et opportunités sur plan, choisie pour son emplacement, sa rareté et sa cohérence d'investissement.",
    "Få tilgang til et konfidensielt utvalg av villaer, leiligheter og nybyggmuligheter, valgt for beliggenhet, sjeldenhet og investeringsmessig sammenheng.",
  ],
  ["Voir la sélection", "Se utvalget"],
  ["Principes S.A.F.E", "S.A.F.E.-prinsipper"],
  ["Lecture S.A.F.E", "S.A.F.E.-analyse"],
  ["Projets étudiés avant présentation.", "Prosjekter analysert før presentasjon."],
  ["clients qualifiés accompagnés", "kvalifiserte kunder fulgt opp"],
  ["Typologies suivies", "Typologier vi følger"],
  ["Villas privées", "Private villaer"],
  ["Appartements Guéliz", "Leiligheter i Guéliz"],
  ["Riads de caractère", "Riad med særpreg"],
  ["Biens sur plan", "Nybyggseiendommer"],
  ["Terrains rares", "Sjeldne tomter"],
  ["Opportunités investisseur", "Investeringsmuligheter"],
  ["QUI SOMMES-NOUS", "HVEM VI ER"],
  [
    "Une maison privée pour lire le marché immobilier de Marrakech avec exigence.",
    "Et privat miljø for å lese eiendomsmarkedet i Marrakech med presisjon.",
  ],
  [
    "OFF MARKET accompagne les acheteurs, investisseurs et propriétaires avec une sélection ciblée, une analyse claire et un accès discret aux opportunités pertinentes.",
    "OFF MARKET følger kjøpere, investorer og eiere med et målrettet utvalg, tydelig analyse og diskret tilgang til relevante muligheter.",
  ],
  ["Sélection ciblée", "Målrettet utvalg"],
  ["Analyse claire", "Tydelig analyse"],
  ["Accompagnement discret", "Diskret veiledning"],
  ["Découvrir notre approche", "Oppdag vår metode"],
  ["QUARTIERS", "OMRÅDER"],
  [
    "Les zones où se construisent les meilleures opportunités",
    "Områdene der de beste mulighetene tar form",
  ],
  ["Les zones où se construisent", "Områdene der"],
  ["les meilleures opportunités", "de beste mulighetene tar form"],
  [
    "Une sélection privée, révélée avec discrétion.",
    "Et privat utvalg, presentert med diskresjon.",
  ],
  [
    "Des biens rares, des adresses confidentielles et une lecture claire avant chaque décision.",
    "Sjeldne eiendommer, konfidensielle adresser og tydelig analyse før hver beslutning.",
  ],
  ["SIMULATEUR PRIVÉ", "PRIVAT KALKULATOR"],
  ["Simuler avant d'investir", "Beregn før du investerer"],
  [
    "Estimez le potentiel d'un bien à Marrakech selon votre usage, puis affinez les chiffres avec",
    "Estimer potensialet til en eiendom i Marrakech etter ditt bruk, og finjuster tallene med",
  ],
  ["Location courte durée", "Korttidsutleie"],
  ["Location longue durée", "Langtidsutleie"],
  ["Achat-revente", "Kjøp og videresalg"],
  ["PARAMÈTRES", "PARAMETERE"],
  [
    "Ajustez vos hypothèses. Le résultat se recalcule en direct.",
    "Juster forutsetningene dine. Resultatet beregnes på nytt fortløpende.",
  ],
  [
    "Estimation indicative. OFF MARKET affine cette simulation avec l'adresse exacte, les charges réelles et les biens disponibles.",
    "Veiledende estimat. OFF MARKET finjusterer beregningen med nøyaktig adresse, reelle kostnader og tilgjengelige eiendommer.",
  ],
  ["Budget d'acquisition", "Kjøpsbudsjett"],
  ["Prix estimé du bien, hors frais.", "Estimert eiendomspris, ekskludert kostnader."],
  ["Prix nuitée moyen", "Gjennomsnittlig nattpris"],
  ["Semaines d'usage personnel", "Uker til egen bruk"],
  ["Taux d'occupation", "Beleggsgrad"],
  ["Loyer mensuel estimé", "Estimert månedlig leie"],
  ["Horizon de revente", "Videresalgshorisont"],
  ["Hypothèse de valorisation annuelle", "Antatt årlig verdistigning"],
  ["RÉSULTAT", "RESULTAT"],
  ["RENDEMENT BRUT ANNUEL", "ÅRLIG BRUTTOAVKASTNING"],
  [
    "avant charges, fiscalité et frais réels",
    "før kostnader, skatt og reelle driftsutgifter",
  ],
  ["Recevoir une analyse privée", "Motta en privat analyse"],
  ["Voir les biens compatibles", "Se passende eiendommer"],
  ["LECTURES PRIVÉES", "PRIVATE ANALYSER"],
  ["Ce que nos clients viennent chercher", "Hva kundene våre søker"],
  ["Afficher le témoignage suivant", "Vis neste anbefaling"],
  ["Suivant", "Neste"],
  [
    "Nous cherchions une opportunité claire, pas une liste de biens. OFF MARKET nous a aidés à comprendre l'adresse, la demande et le potentiel avant même la première visite.",
    "Vi lette etter en tydelig mulighet, ikke en liste over eiendommer. OFF MARKET hjalp oss å forstå adressen, etterspørselen og potensialet allerede før første visning.",
  ],
  [
    "Nous cherchions une opportunité claire, pas une liste de biens. OFF MARKET nous a aidés à comprendre l’adresse, la demande et le potentiel avant même la première visite.",
    "Vi lette etter en tydelig mulighet, ikke en liste over eiendommer. OFF MARKET hjalp oss å forstå adressen, etterspørselen og potensialet allerede før første visning.",
  ],
  [
    "La différence s’est faite dans la lecture du marché : comparables, risques, marge de négociation et cohérence patrimoniale. La décision est devenue beaucoup plus simple.",
    "Forskjellen lå i markedsanalysen: sammenlignbare objekter, risiko, forhandlingsrom og formuesmessig sammenheng. Beslutningen ble langt enklere.",
  ],
  [
    "Nous avons apprécié la discrétion, le tri et la qualité des échanges. Les biens présentés étaient peu nombreux, mais réellement alignés avec notre projet.",
    "Vi satte pris på diskresjonen, filtreringen og kvaliteten i dialogen. Eiendommene som ble presentert var få, men virkelig i tråd med prosjektet vårt.",
  ],
  ["Acheteur privé", "Privat kjøper"],
  ["Investisseur", "Investor"],
  ["Client accompagné", "Kunde fulgt opp"],
  ["Résidence secondaire · Marrakech", "Feriebolig · Marrakech"],
  ["Appartement premium · Guéliz / Hivernage", "Premiumleilighet · Guéliz / Hivernage"],
  ["Riad de caractère · Médina", "Riad med særpreg · Medina"],
  ["ACCÈS PRIVÉ", "PRIVAT TILGANG"],
  ["Recevoir la sélection off-market", "Motta off-market utvalget"],
  [
    "Remplissez le formulaire pour accéder aux projets confidentiels et recevoir une sélection privée adaptée à votre budget.",
    "Fyll ut skjemaet for å få tilgang til konfidensielle prosjekter og motta et privat utvalg tilpasset budsjettet ditt.",
  ],
  ["Nom complet", "Fullt navn"],
  ["Numéro de téléphone", "Telefonnummer"],
  ["Indicatif pays", "Landkode"],
  ["Numéro", "Nummer"],
  ["Sélectionnez votre budget", "Velg budsjett"],
  ["Message (optionnel)", "Melding (valgfritt)"],
  [
    "En cliquant sur le bouton, vous acceptez que OFF MARKET vous contacte au sujet de votre demande.",
    "Ved å klikke på knappen godtar du at OFF MARKET kontakter deg om forespørselen din.",
  ],
  ["Confidentialité", "Personvern"],
  ["Tous droits réservés", "Alle rettigheter forbeholdt"],
  ["Mentions légales", "Juridisk merknad"],
  ["politique de confidentialité", "personvernerklæring"],
  ["Sélection :", "Utvalg:"],
  ["Navigation fiche bien", "Navigasjon i eiendomsprofil"],
  ["Fermer la fiche", "Lukk eiendomsprofilen"],
  ["Plans transmis sur demande", "Plantegninger på forespørsel"],
  ["Rappel", "Tilbakeringing"],
  ["PARLONS-EN", "LA OSS SNAKKE"],
  ["Votre projet mérite une lecture privée.", "Prosjektet ditt fortjener en privat analyse."],
  ["Dites-nous ce que vous recherchez.", "Fortell oss hva du leter etter."],
  [
    "OFF MARKET vous répond avec une sélection ciblée, une analyse claire et un accompagnement discret.",
    "OFF MARKET svarer med et målrettet utvalg, tydelig analyse og diskret veiledning.",
  ],
  [
    " vous répond avec une sélection ciblée, une analyse claire et un accompagnement discret.",
    " svarer med et målrettet utvalg, tydelig analyse og diskret veiledning.",
  ],
  ["Demander un accès privé", "Be om privat tilgang"],
  ["Parler à un conseiller", "Snakk med en rådgiver"],
  ["Veuillez pivoter votre appareil", "Roter enheten din"],
  ["to portrait mode", "til stående format"],
  ["to landscape mode", "til liggende format"],
  ["to&nbsp;portrait mode", "til stående format"],
  ["to&nbsp;landscape mode", "til liggende format"],
  ["to portrait mode", "til stående format"],
  ["to landscape mode", "til liggende format"],
  ["Private properties", "Private eiendommer"],
  ["Contact us", "Kontakt"],
  ["Our story", "Vår historie"],
  ["Off-plan", "Nybygg"],
  ["Back to top", "Tilbake til toppen"],
  ["Private real estate in Marrakech", "Privat eiendom i Marrakech"],
  ["Choose language", "Velg språk"],
  ["Main navigation", "Hovednavigasjon"],
  ["Maison OFF MARKET", "OFF MARKET"],
  ["Sélection privée d'opportunités immobilières à Marrakech.", "Privat utvalg av eiendomsmuligheter i Marrakech."],
  ["OFF MARKET — page d&amp;rsquo;accueil", "OFF MARKET — hjem"],
  ["call time", "Tidspunkt for samtale"],
  ["Envoyer<br>\n                    une demande", "Send<br>\n                    en forespørsel"],
  ["Envoyer une demande", "Send en forespørsel"],
];

const ROUTE_REPLACEMENTS: Record<"en" | "es" | "it" | "nl" | "no", readonly Replacement[]> = {
  en: [
    ['href="/"', 'href="/en/"'],
    ['href="/about/"', 'href="/en/about/"'],
    ['href="/quartiers/"', 'href="/en/neighbourhoods/"'],
    ['href="/nos-projets/"', 'href="/en/projects/"'],
    ['href="/simulateur/"', 'href="/en/simulator/"'],
    ['href="/simulateur"', 'href="/en/simulator/"'],
    ['href="/sur-plan/"', 'href="/en/off-plan/"'],
    ['href="/sur-plan"', 'href="/en/off-plan/"'],
    ['href="/contact/"', 'href="/en/contact/"'],
    ['href="/contact"', 'href="/en/contact/"'],
    ['href="/off-market/"', 'href="/en/off-market/"'],
    ['href="/off-market"', 'href="/en/off-market/"'],
    ['href="/blog/"', 'href="/en/blog/"'],
    ['href="/blog"', 'href="/en/blog/"'],
    ['href="/privacy-policy/"', 'href="/en/privacy-policy/"'],
    ['href="/about/#acteurs-verifies"', 'href="/en/about/#acteurs-verifies"'],
  ],
  es: [
    ['href="/"', 'href="/es/"'],
    ['href="/about/"', 'href="/es/sobre-nosotros/"'],
    ['href="/quartiers/"', 'href="/es/barrios/"'],
    ['href="/nos-projets/"', 'href="/es/proyectos/"'],
    ['href="/simulateur/"', 'href="/es/simulador/"'],
    ['href="/simulateur"', 'href="/es/simulador/"'],
    ['href="/sur-plan/"', 'href="/es/sobre-plano/"'],
    ['href="/sur-plan"', 'href="/es/sobre-plano/"'],
    ['href="/contact/"', 'href="/es/contacto/"'],
    ['href="/contact"', 'href="/es/contacto/"'],
    ['href="/off-market/"', 'href="/es/off-market/"'],
    ['href="/off-market"', 'href="/es/off-market/"'],
    ['href="/blog/"', 'href="/es/blog/"'],
    ['href="/blog"', 'href="/es/blog/"'],
    ['href="/privacy-policy/"', 'href="/es/politica-de-privacidad/"'],
    ['href="/about/#acteurs-verifies"', 'href="/es/sobre-nosotros/#acteurs-verifies"'],
    ['href="/en/"', 'href="/es/"'],
    ['href="/en/contact/"', 'href="/es/contacto/"'],
    ['href="/en/off-market/"', 'href="/es/off-market/"'],
    ['href="/en/off-plan/"', 'href="/es/sobre-plano/"'],
    ['href="/en/blog/"', 'href="/es/blog/"'],
    ['data-lang="EN">EN', 'data-lang="ES">ES'],
  ],
  nl: [
    ['href="/"', 'href="/nl/"'],
    ['href="/about/"', 'href="/nl/over-ons/"'],
    ['href="/quartiers/"', 'href="/nl/wijken/"'],
    ['href="/nos-projets/"', 'href="/nl/projecten/"'],
    ['href="/simulateur/"', 'href="/nl/simulator/"'],
    ['href="/simulateur"', 'href="/nl/simulator/"'],
    ['href="/sur-plan/"', 'href="/nl/nieuwbouw/"'],
    ['href="/sur-plan"', 'href="/nl/nieuwbouw/"'],
    ['href="/contact/"', 'href="/nl/contact/"'],
    ['href="/contact"', 'href="/nl/contact/"'],
    ['href="/off-market/"', 'href="/nl/off-market/"'],
    ['href="/off-market"', 'href="/nl/off-market/"'],
    ['href="/blog/"', 'href="/nl/blog/"'],
    ['href="/blog"', 'href="/nl/blog/"'],
    ['href="/privacy-policy/"', 'href="/nl/privacybeleid/"'],
    ['href="/about/#acteurs-verifies"', 'href="/nl/over-ons/#acteurs-verifies"'],
    ['href="/en/"', 'href="/nl/"'],
    ['href="/en/contact/"', 'href="/nl/contact/"'],
    ['href="/en/off-market/"', 'href="/nl/off-market/"'],
    ['href="/en/off-plan/"', 'href="/nl/nieuwbouw/"'],
    ['href="/en/blog/"', 'href="/nl/blog/"'],
    ['data-lang="EN">EN', 'data-lang="NL">NL'],
  ],
  it: [
    ['href="/"', 'href="/it/"'],
    ['href="/about/"', 'href="/it/chi-siamo/"'],
    ['href="/quartiers/"', 'href="/it/quartieri/"'],
    ['href="/nos-projets/"', 'href="/it/progetti/"'],
    ['href="/simulateur/"', 'href="/it/simulatore/"'],
    ['href="/simulateur"', 'href="/it/simulatore/"'],
    ['href="/sur-plan/"', 'href="/it/progetti-su-piano/"'],
    ['href="/sur-plan"', 'href="/it/progetti-su-piano/"'],
    ['href="/contact/"', 'href="/it/contatto/"'],
    ['href="/contact"', 'href="/it/contatto/"'],
    ['href="/off-market/"', 'href="/it/off-market/"'],
    ['href="/off-market"', 'href="/it/off-market/"'],
    ['href="/blog/"', 'href="/it/blog/"'],
    ['href="/blog"', 'href="/it/blog/"'],
    ['href="/privacy-policy/"', 'href="/it/privacy-policy/"'],
    ['href="/about/#acteurs-verifies"', 'href="/it/chi-siamo/#acteurs-verifies"'],
    ['href="/fr/sur-plan/"', 'href="/it/progetti-su-piano/"'],
    ['href="/contact/"', 'href="/it/contatto/"'],
    ['href="/fr/about/"', 'href="/it/chi-siamo/"'],
    ['href="/fr/" class="is-active"', 'href="/it/" class="is-active"'],
    ['href="/fr/" class="cinematic-menu-link"', 'href="/it/" class="cinematic-menu-link"'],
    [
      'href="/fr/" class="om-language-dropdown__option is-active"',
      'href="/it/" class="om-language-dropdown__option is-active"',
    ],
    [
      'href="/fr/" class="mv-lang-switcher__btn is-active"',
      'href="/it/" class="mv-lang-switcher__btn is-active"',
    ],
    ['data-lang="FR">FR', 'data-lang="IT">IT'],
    ['href="/it/">La nostra storia', 'href="/it/chi-siamo/">La nostra storia'],
  ],
  no: [
    ['href="/"', 'href="/no/"'],
    ['href="/about/"', 'href="/no/om-oss/"'],
    ['href="/quartiers/"', 'href="/no/omrader/"'],
    ['href="/nos-projets/"', 'href="/no/prosjekter/"'],
    ['href="/simulateur/"', 'href="/no/kalkulator/"'],
    ['href="/simulateur"', 'href="/no/kalkulator/"'],
    ['href="/sur-plan/"', 'href="/no/nybygg/"'],
    ['href="/sur-plan"', 'href="/no/nybygg/"'],
    ['href="/contact/"', 'href="/no/kontakt/"'],
    ['href="/contact"', 'href="/no/kontakt/"'],
    ['href="/off-market/"', 'href="/no/off-market/"'],
    ['href="/off-market"', 'href="/no/off-market/"'],
    ['href="/blog/"', 'href="/no/blogg/"'],
    ['href="/blog"', 'href="/no/blogg/"'],
    ['href="/privacy-policy/"', 'href="/no/personvernerklaering/"'],
    ['href="/about/#acteurs-verifies"', 'href="/no/om-oss/#acteurs-verifies"'],
    ['href="/en/"', 'href="/no/"'],
    ['href="/en/contact/"', 'href="/no/kontakt/"'],
    ['href="/en/off-market/"', 'href="/no/off-market/"'],
    ['href="/en/off-plan/"', 'href="/no/nybygg/"'],
    ['href="/en/blog/"', 'href="/no/blogg/"'],
    ['data-lang="EN">EN', 'data-lang="NO">NO'],
  ],
};

function getReplacements(locale: SiteLocale): readonly Replacement[] {
  if (locale === "en") return [...ROUTE_REPLACEMENTS.en, ...EN_REPLACEMENTS];
  if (locale === "es") return [...ROUTE_REPLACEMENTS.es, ...ES_REPLACEMENTS];
  if (locale === "nl") return [...ROUTE_REPLACEMENTS.nl, ...NL_REPLACEMENTS];
  if (locale === "it") return [...ROUTE_REPLACEMENTS.it, ...IT_REPLACEMENTS];
  if (locale === "no") return [...ROUTE_REPLACEMENTS.no, ...NO_REPLACEMENTS];
  return [];
}

function applyReplacements(value: string, replacements: readonly Replacement[]): string {
  const tokens = new Map<string, string>();
  let result = value;

  const escapeRegExp = (text: string) => text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

  // Tokenize every source phrase before restoring translations so generated text
  // can never become input for a later replacement.
  [...replacements]
    .sort((a, b) => b[0].length - a[0].length)
    .forEach(([from, to], index) => {
      const token = `\u0000OM_LOC_${index}\u0000`;
      if (/^[\p{L}\p{N}][\p{L}\p{N}.'’-]*$/u.test(from)) {
        const pattern = new RegExp(
          `(?<![\\p{L}\\p{N}])${escapeRegExp(from)}(?![\\p{L}\\p{N}])`,
          "gu",
        );
        result = result.replace(pattern, token);
      } else {
        result = result.split(from).join(token);
      }
      tokens.set(token, to);
    });

  tokens.forEach((to, token) => {
    result = result.split(token).join(to);
  });

  return result;
}

export function localizeHomeLegacyHtml(html: string, locale: SiteLocale): string {
  const replacements = getReplacements(locale);
  if (!replacements.length) return html;

  const localized = applyReplacements(html, replacements);
  if (locale !== "nl") return localized;

  return localized.replace(
    /(?:Door te klikken accepteert u onze|En cliquant, vous acceptez notre)\s*<br>\s*(?:onze|à notre)\s*(<a\b[^>]*>)(?:politique de confidentialité|privacybeleid)(<\/a>)/gi,
    "Door te klikken, gaat u akkoord met ons<br>$1privacybeleid$2",
  );
}

export function localizeHomeLegacySegments(
  segments: BodySegment[],
  locale: SiteLocale,
): BodySegment[] {
  if (
    locale !== "en" &&
    locale !== "es" &&
    locale !== "nl" &&
    locale !== "it" &&
    locale !== "no"
  ) return segments;

  return segments.map((segment) =>
    segment.kind === "html"
      ? { ...segment, html: localizeHomeLegacyHtml(segment.html, locale) }
      : segment,
  );
}
