export { SITE_URL, PRODUCTION_URLS, SITEMAP_URLS } from "@/lib/legacy/routes";

export const LANG_LINKS = {
  home: { en: "/en/", es: "/es/", fr: "/", it: "/it/", nl: "/nl/", no: "/no/" },
  about: { en: "/en/about/", es: "/es/sobre-nosotros/", fr: "/about/", it: "/it/chi-siamo/", nl: "/nl/over-ons/", no: "/no/om-oss/" },
  frAbout: { en: "/en/about/", es: "/es/sobre-nosotros/", fr: "/about/", it: "/it/chi-siamo/", nl: "/nl/over-ons/", no: "/no/om-oss/" },
  quartiers: { en: "/en/neighbourhoods/", es: "/es/barrios/", fr: "/quartiers/", it: "/it/quartieri/", nl: "/nl/wijken/", no: "/no/omrader/" },
  nosProjets: { en: "/en/projects/", es: "/es/proyectos/", fr: "/nos-projets/", it: "/it/progetti/", nl: "/nl/projecten/", no: "/no/prosjekter/" },
  offPlan: {
    en: "/en/off-plan/",
    es: "/es/sobre-plano/",
    fr: "/sur-plan/",
    it: "/it/progetti-su-piano/",
    nl: "/nl/nieuwbouw/",
    no: "/no/nybygg/",
  },
  offMarket: {
    en: "/en/off-market/",
    es: "/es/off-market/",
    fr: "/off-market/",
    it: "/it/off-market/",
    nl: "/nl/off-market/",
    no: "/no/off-market/",
  },
  villaJaz: {
    en: "/en/off-plan/villa-jaz/",
    es: "/es/sobre-plano/villa-jaz/",
    fr: "/sur-plan/villa-jaz/",
    it: "/it/progetti-su-piano/villa-jaz/",
    nl: "/nl/nieuwbouw/villa-jaz/",
    no: "/no/nybygg/villa-jaz/",
  },
  simulator: {
    en: "/en/simulator/",
    es: "/es/simulador/",
    fr: "/simulateur/",
    it: "/it/simulatore/",
    nl: "/nl/simulator/",
    no: "/no/kalkulator/",
  },
  blog: {
    en: "/en/blog/",
    es: "/es/blog/",
    fr: "/blog/",
    it: "/it/blog/",
    nl: "/nl/blog/",
    no: "/no/blogg/",
  },
  privacy: {
    en: "/en/privacy-policy/",
    es: "/es/politica-de-privacidad/",
    fr: "/privacy-policy/",
    it: "/it/privacy-policy/",
    nl: "/nl/privacybeleid/",
    no: "/no/personvernerklaering/",
  },
  contact: {
    en: "/en/contact/",
    es: "/es/contacto/",
    fr: "/contact/",
    it: "/it/contatto/",
    nl: "/nl/contact/",
    no: "/no/kontakt/",
  },
} as const;
