/**
 * Production URL registry — sitemap, migration tracking.
 * Legacy HTML bridge removed in Phase 8; static HTML lives under
 * `_legacy_static_archived_after_full_next_migration/` (parsed by Next.js).
 */
export const BLOCKED_PATH_PREFIXES = [
  "archive",
  "archives",
  "_backup_static_before_next_migration",
  "_legacy_static_archived_after_full_next_migration",
  "node_modules",
  ".next",
  "scripts",
  "docs",
  "media",
  "app",
  "lib",
  "components",
  "public",
] as const;

/** @deprecated Bridge removed — kept empty for reference only */
export const EXPLICIT_LEGACY_ROUTES: Record<string, string> = {};

/**
 * All known production URL paths (trailing slash normalized away for lookup).
 * Used for sitemap generation and migration tracking.
 */
export const PRODUCTION_URLS = [
  "/",
  "/fr",
  "/en",
  "/es",
  "/it",
  "/nl",
  "/no",
  "/about",
  "/en/about",
  "/es/sobre-nosotros",
  "/it/chi-siamo",
  "/nl/over-ons",
  "/no/om-oss",
  "/fr/about",
  "/quartiers",
  "/en/neighbourhoods",
  "/es/barrios",
  "/it/quartieri",
  "/nl/wijken",
  "/no/omrader",
  "/nos-projets",
  "/en/projects",
  "/es/proyectos",
  "/it/progetti",
  "/nl/projecten",
  "/no/prosjekter",
  "/contact",
  "/fr/contact",
  "/en/contact",
  "/es/contacto",
  "/nl/contact",
  "/it/contatto",
  "/no/kontakt",
  "/off-market",
  "/en/off-market",
  "/es/off-market",
  "/nl/off-market",
  "/it/off-market",
  "/no/off-market",
  "/sur-plan",
  "/sur-plan/villa-jaz",
  "/fr/sur-plan",
  "/en/off-plan",
  "/en/off-plan/villa-jaz",
  "/es/sobre-plano",
  "/es/sobre-plano/villa-jaz",
  "/it/progetti-su-piano/villa-jaz",
  "/it/progetti-su-piano",
  "/nl/nieuwbouw",
  "/nl/nieuwbouw/villa-jaz",
  "/no/nybygg",
  "/no/nybygg/villa-jaz",
  "/location",
  "/simulateur",
  "/en/simulator",
  "/es/simulador",
  "/it/simulatore",
  "/nl/simulator",
  "/no/kalkulator",
  "/privacy-policy",
  "/conditions-generales",
  "/mentions-legales",
  "/en/privacy-policy",
  "/en/terms-of-use",
  "/en/legal-notice",
  "/es/politica-de-privacidad",
  "/es/condiciones-de-uso",
  "/es/aviso-legal",
  "/it/privacy-policy",
  "/it/condizioni-d-uso",
  "/it/note-legali",
  "/nl/privacybeleid",
  "/nl/gebruiksvoorwaarden",
  "/nl/wettelijke-vermeldingen",
  "/no/personvernerklaering",
  "/no/bruksvilkaar",
  "/no/juridisk-merknad",
  "/blog",
  "/en/blog",
  "/es/blog",
  "/it/blog",
  "/nl/blog",
  "/no/blogg",
  "/blog/acheter-villa-sur-plan-marrakech",
  "/blog/investir-immobilier-luxe-marrakech",
  "/blog/adresses-immobilier-marrakech",
  "/blog/off-market-marrakech-biens-confidentiels",
  "/blog/appartement-hypercentre-gueliz-marrakech",
  "/en/blog/buying-off-plan-villa-marrakech",
  "/es/blog/comprar-villa-sobre-plano-marrakech",
  "/it/blog/acquistare-villa-su-progetto-marrakech",
  "/en/blog/luxury-real-estate-investment-marrakech",
  "/es/blog/invertir-inmobiliario-lujo-marrakech",
  "/it/blog/investire-immobiliare-di-lusso-marrakech",
  "/en/blog/best-addresses-real-estate-marrakech",
  "/es/blog/mejores-zonas-inmobiliarias-marrakech",
  "/it/blog/indirizzi-immobiliari-marrakech",
  "/en/blog/off-market-properties-marrakech",
  "/es/blog/inmuebles-off-market-marrakech",
  "/it/blog/immobili-off-market-marrakech",
  "/en/blog/apartment-hypercentre-gueliz-marrakech",
  "/es/blog/apartamento-centro-gueliz-marrakech",
  "/it/blog/appartamento-centro-gueliz-marrakech",
  "/nl/blog/nieuwbouwvilla-kopen-marrakech",
  "/nl/blog/investeren-luxe-vastgoed-marrakech",
  "/nl/blog/beste-adressen-vastgoed-marrakech",
  "/nl/blog/off-market-vastgoed-marrakech",
  "/nl/blog/appartement-hypercentre-gueliz-marrakech",
  "/no/blogg/kjope-nybyggvilla-marrakech",
  "/no/blogg/investere-luksus-eiendom-marrakech",
  "/no/blogg/beste-omrader-eiendom-marrakech",
  "/no/blogg/off-market-eiendom-marrakech",
  "/no/blogg/leilighet-sentrum-gueliz-marrakech",
] as const;

export const SITE_URL = "https://offmarketofficial.com";

export const SITEMAP_URLS: Array<{
  path: string;
  changefreq: "weekly" | "monthly" | "yearly";
  priority: number;
}> = [
  { path: "/", changefreq: "weekly", priority: 1.0 },
  { path: "/en/", changefreq: "weekly", priority: 1.0 },
  { path: "/es/", changefreq: "weekly", priority: 1.0 },
  { path: "/it/", changefreq: "weekly", priority: 1.0 },
  { path: "/nl/", changefreq: "weekly", priority: 1.0 },
  { path: "/no/", changefreq: "weekly", priority: 1.0 },
  { path: "/sur-plan/", changefreq: "monthly", priority: 0.9 },
  { path: "/en/off-plan/", changefreq: "monthly", priority: 0.9 },
  { path: "/es/sobre-plano/", changefreq: "monthly", priority: 0.9 },
  { path: "/it/progetti-su-piano/", changefreq: "monthly", priority: 0.9 },
  { path: "/nl/nieuwbouw/", changefreq: "monthly", priority: 0.9 },
  { path: "/no/nybygg/", changefreq: "monthly", priority: 0.9 },
  { path: "/sur-plan/villa-jaz/", changefreq: "monthly", priority: 0.85 },
  { path: "/en/off-plan/villa-jaz/", changefreq: "monthly", priority: 0.85 },
  { path: "/es/sobre-plano/villa-jaz/", changefreq: "monthly", priority: 0.85 },
  { path: "/it/progetti-su-piano/villa-jaz/", changefreq: "monthly", priority: 0.85 },
  { path: "/nl/nieuwbouw/villa-jaz/", changefreq: "monthly", priority: 0.85 },
  { path: "/no/nybygg/villa-jaz/", changefreq: "monthly", priority: 0.85 },
  { path: "/about/", changefreq: "monthly", priority: 0.85 },
  { path: "/en/about/", changefreq: "monthly", priority: 0.85 },
  { path: "/es/sobre-nosotros/", changefreq: "monthly", priority: 0.85 },
  { path: "/it/chi-siamo/", changefreq: "monthly", priority: 0.85 },
  { path: "/nl/over-ons/", changefreq: "monthly", priority: 0.85 },
  { path: "/no/om-oss/", changefreq: "monthly", priority: 0.85 },
  { path: "/quartiers/", changefreq: "monthly", priority: 0.85 },
  { path: "/en/neighbourhoods/", changefreq: "monthly", priority: 0.85 },
  { path: "/es/barrios/", changefreq: "monthly", priority: 0.85 },
  { path: "/it/quartieri/", changefreq: "monthly", priority: 0.85 },
  { path: "/nl/wijken/", changefreq: "monthly", priority: 0.85 },
  { path: "/no/omrader/", changefreq: "monthly", priority: 0.85 },
  { path: "/nos-projets/", changefreq: "monthly", priority: 0.85 },
  { path: "/en/projects/", changefreq: "monthly", priority: 0.85 },
  { path: "/es/proyectos/", changefreq: "monthly", priority: 0.85 },
  { path: "/it/progetti/", changefreq: "monthly", priority: 0.85 },
  { path: "/nl/projecten/", changefreq: "monthly", priority: 0.85 },
  { path: "/no/prosjekter/", changefreq: "monthly", priority: 0.85 },
  { path: "/off-market/", changefreq: "monthly", priority: 0.9 },
  { path: "/en/off-market/", changefreq: "monthly", priority: 0.9 },
  { path: "/es/off-market/", changefreq: "monthly", priority: 0.9 },
  { path: "/it/off-market/", changefreq: "monthly", priority: 0.9 },
  { path: "/nl/off-market/", changefreq: "monthly", priority: 0.9 },
  { path: "/no/off-market/", changefreq: "monthly", priority: 0.9 },
  { path: "/contact/", changefreq: "monthly", priority: 0.8 },
  { path: "/en/contact/", changefreq: "monthly", priority: 0.8 },
  { path: "/es/contacto/", changefreq: "monthly", priority: 0.8 },
  { path: "/it/contatto/", changefreq: "monthly", priority: 0.8 },
  { path: "/nl/contact/", changefreq: "monthly", priority: 0.8 },
  { path: "/no/kontakt/", changefreq: "monthly", priority: 0.8 },
  { path: "/blog/", changefreq: "weekly", priority: 0.85 },
  { path: "/en/blog/", changefreq: "weekly", priority: 0.85 },
  { path: "/es/blog/", changefreq: "weekly", priority: 0.85 },
  { path: "/it/blog/", changefreq: "weekly", priority: 0.85 },
  { path: "/nl/blog/", changefreq: "weekly", priority: 0.85 },
  { path: "/no/blogg/", changefreq: "weekly", priority: 0.85 },
  {
    path: "/blog/acheter-villa-sur-plan-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/blog/investir-immobilier-luxe-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/blog/adresses-immobilier-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/blog/off-market-marrakech-biens-confidentiels/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/blog/appartement-hypercentre-gueliz-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/en/blog/buying-off-plan-villa-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/es/blog/comprar-villa-sobre-plano-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/it/blog/acquistare-villa-su-progetto-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/en/blog/luxury-real-estate-investment-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/es/blog/invertir-inmobiliario-lujo-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/it/blog/investire-immobiliare-di-lusso-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/en/blog/best-addresses-real-estate-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/es/blog/mejores-zonas-inmobiliarias-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/it/blog/indirizzi-immobiliari-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/en/blog/off-market-properties-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/es/blog/inmuebles-off-market-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/it/blog/immobili-off-market-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/en/blog/apartment-hypercentre-gueliz-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/es/blog/apartamento-centro-gueliz-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/it/blog/appartamento-centro-gueliz-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/nl/blog/nieuwbouwvilla-kopen-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/nl/blog/investeren-luxe-vastgoed-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/nl/blog/beste-adressen-vastgoed-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/nl/blog/off-market-vastgoed-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/nl/blog/appartement-hypercentre-gueliz-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/no/blogg/kjope-nybyggvilla-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/no/blogg/investere-luksus-eiendom-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/no/blogg/beste-omrader-eiendom-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/no/blogg/off-market-eiendom-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  {
    path: "/no/blogg/leilighet-sentrum-gueliz-marrakech/",
    changefreq: "monthly",
    priority: 0.7,
  },
  { path: "/simulateur/", changefreq: "monthly", priority: 0.9 },
  { path: "/en/simulator/", changefreq: "monthly", priority: 0.9 },
  { path: "/es/simulador/", changefreq: "monthly", priority: 0.9 },
  { path: "/it/simulatore/", changefreq: "monthly", priority: 0.9 },
  { path: "/nl/simulator/", changefreq: "monthly", priority: 0.9 },
  { path: "/no/kalkulator/", changefreq: "monthly", priority: 0.9 },
  { path: "/privacy-policy/", changefreq: "yearly", priority: 0.3 },
  { path: "/conditions-generales/", changefreq: "yearly", priority: 0.3 },
  { path: "/mentions-legales/", changefreq: "yearly", priority: 0.3 },
  { path: "/en/privacy-policy/", changefreq: "yearly", priority: 0.3 },
  { path: "/en/terms-of-use/", changefreq: "yearly", priority: 0.3 },
  { path: "/en/legal-notice/", changefreq: "yearly", priority: 0.3 },
  { path: "/es/politica-de-privacidad/", changefreq: "yearly", priority: 0.3 },
  { path: "/es/condiciones-de-uso/", changefreq: "yearly", priority: 0.3 },
  { path: "/es/aviso-legal/", changefreq: "yearly", priority: 0.3 },
  { path: "/it/privacy-policy/", changefreq: "yearly", priority: 0.3 },
  { path: "/it/condizioni-d-uso/", changefreq: "yearly", priority: 0.3 },
  { path: "/it/note-legali/", changefreq: "yearly", priority: 0.3 },
  { path: "/nl/privacybeleid/", changefreq: "yearly", priority: 0.3 },
  { path: "/nl/gebruiksvoorwaarden/", changefreq: "yearly", priority: 0.3 },
  { path: "/nl/wettelijke-vermeldingen/", changefreq: "yearly", priority: 0.3 },
  { path: "/no/personvernerklaering/", changefreq: "yearly", priority: 0.3 },
  { path: "/no/bruksvilkaar/", changefreq: "yearly", priority: 0.3 },
  { path: "/no/juridisk-merknad/", changefreq: "yearly", priority: 0.3 },
];
